[workspace]
members = [
  ".",
  "cli",
  "lichess",
  "lichess-client",
]

[workspace.package]
authors = ["RustChess Engineers"]
edition = "2024"
version = "0.1.0-dev"

[workspace.dependencies]
# chess-cli.path = "cli"
chess-lichess.path = "lichess"
chess-lichess-client = { version = "2.0.110", path = "lichess-client" }
rustchess.path = "."

anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["cargo", "color", "derive"] }
# clap-verbosity-flag = "3"
# clio = { version = "0.3", features = ["clap-parse"] }
encoding_rs = "0.8"
enumflags2 = "0.7"
oauth2 = "5"
progenitor-client = "0.13"
rand = { version = "0.10", features = ["chacha"] }
reqwest = { version = "0.13", features = ["json", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "3"
ciborium = "0.2"
sha2-const = "0.1"
# sqlx  = { version = "0.8", features = ["sqlite"] }
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt"] }
url = "2"
winnow = "1"

[package]
name = "rustchess"
authors.workspace = true
edition.workspace = true
version.workspace = true

[lib]
name = "chess"

[features]
default = []
empty-id = []
const-fn-standard-id = []
lichess = ["dep:chess-lichess"]
serde = ["dep:serde", "dep:serde_with"]

[dependencies]
chess-lichess = { workspace = true, optional = true }

encoding_rs.workspace = true
enumflags2.workspace = true
rand.workspace = true
sha2-const.workspace = true
thiserror.workspace = true
winnow.workspace = true

serde = { workspace = true, optional = true }
serde_with = { workspace = true, optional = true }

[dev-dependencies]
anyhow.workspace = true
ciborium.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true

rustchess = { path = ".", features = ["serde"] }

# [patch.crates-io.typify-impl]
# path = "lichess/vendor/typify/typify-impl"
