[package]
name = "rust-chess"
authors.workspace = true
edition.workspace = true
version.workspace = true

[lib]
name = "chess"

[features]
default = []
serde = ["dep:serde", "macros/serde"]

[dependencies]
arbitrary.workspace = true
encoding_rs.workspace = true
rand.workspace = true
sha2-const.workspace = true
thiserror.workspace = true
macros.workspace = true
winnow.workspace = true

serde = { workspace = true, optional = true }

[dev-dependencies]
chess = { workspace = true, features = ["serde"] }

anyhow.workspace = true
hex-literal.workspace = true
serde.workspace = true
serde_json.workspace = true


[package.metadata.cargo-shear]
ignored-paths = [
  "src/game/storage.rs",
  "src/id/POLYGLOT-BASIS.rs",
  "src/id/STANDARD-BASIS.rs",
  "src/square/SLIDER-SIGHTS.rs",
]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  "cfg(rust_chess_compile_time_polyglot_basis)",
  "cfg(rust_chess_compile_time_slider_sights)",
  "cfg(rust_chess_compile_time_standard_basis)",
] }

[workspace]
members = [".", "bin", "macros", "macros-impl"]
default-members = [".", "bin"]

[workspace.package]
authors = ["RustChess Engineers"]
edition = "2024"
version = "0.1.0-dev"

[workspace.dependencies]
chess = { package = "rust-chess", path = "." }
macros = { package = "rust-chess-macros", path = "macros" }
macros-impl = { package = "rust-chess-macros-impl", path = "macros-impl" }

anyhow = "1"
arbitrary = "1"
clap = { version = "4", features = ["cargo", "color"] }
clap_derive = "4"
derive_arbitrary = "1"
encoding_rs = "0.8"
hex-literal = "1"
proc-macro2 = "1"
quote = "1"
rand = { version = "0.10", features = ["chacha"] }
serde = "1"
serde_derive = "1"
serde_json = "1"
sha2-const = "0.1"
thiserror = "2"
tracing = "0.1"
syn = "3"
winnow = "1"
