[package]
name = "rust-chess-macros-impl"
authors.workspace = true
edition.workspace = true
version.workspace = true

[lib]
name = "macros_impl"
proc-macro = true

[features]
default = []
serde = ["dep:proc-macro2", "dep:quote", "dep:syn"]

[dependencies]
proc-macro2 = { workspace = true, optional = true }
quote = { workspace = true, optional = true }
syn = { workspace = true, optional = true }
