#!/usr/bin/env rust-script
//! ```cargo
//! [dependencies]
//! rustchess = { path = "..", features = ["const-fn-statics"] }
//! ```

use std::{
    fs,
    io::{self, BufWriter, Write},
};

use chess::{Board, Id, Scharnagl};

fn main() -> io::Result<()> {
    let mut table = Vec::with_capacity(960);
    for i in 0..960 {
        let scharnagl = Scharnagl::new(i).unwrap();
        table.push((Board::freestyle(scharnagl).standard_id(), scharnagl));
    }
    table.sort_by_key(|(id, _)| *id);

    let file = fs::File::create("src/board/scharnagl-id.rs")?;
    let mut writer = BufWriter::new(file);

    writeln!(writer, "// Generated by scripts/scharnagl-id.rs.")?;
    writeln!(writer, "pub static SCHARNAGL_BY_ID: [(Id, Scharnagl); 960] = [")?;
    for (id, scharnagl) in table {
        writeln!(writer, "    (Id({}), Scharnagl({scharnagl})),", hex(id))?;
    }
    writeln!(writer, "];")
}

fn hex(id: Id) -> String {
    let hex = format!("{:032x}", id.0);
    let mut grouped = String::with_capacity(39);
    for (index, digit) in hex.chars().enumerate() {
        if index > 0 && index % 4 == 0 {
            grouped.push('_');
        }
        grouped.push(digit);
    }
    format!("0x{grouped}")
}
