#!/usr/bin/env rust-script
//! ```cargo
//! [dependencies]
//! rustchess = { path = ".." }
//! ```

use std::{
    fs::File,
    io::{self, BufWriter, Write},
};

fn main() -> std::io::Result<()> {
    let table = chess::moves::SliderSights::volker_annuss().into_array();
    write_rust(&table)?;
    write_text(&table)?;

    Ok(())
}

fn write_rust(table: &[chess::bitboard::Bitboard; 88772]) -> io::Result<()> {
    let file = File::create("src/slider_sights.rs")?;
    let mut writer = BufWriter::new(file);

    writeln!(writer, "// Generated by scripts/slider_sights.rs.")?;
    writeln!(writer, "static SLIDER_SIGHTS: SliderSights = SliderSights([")?;
    for sight in table {
        writeln!(writer, "    Bitboard({}),", sight.0)?;
    }
    writeln!(writer, "]);")?;

    Ok(())
}

fn write_text(table: &[chess::bitboard::Bitboard; 88772]) -> io::Result<()> {
    let file = File::create("slider_sights.txt")?;
    let mut writer = BufWriter::new(file);

    for sight in table {
        writeln!(writer, "{}", sight.0)?;
    }

    Ok(())
}
