#!/usr/bin/env rust-script
//! ```cargo
//! [dependencies]
//! chess = { package = "rust-chess", path = ".." }
//! ```

use std::{
    env,
    fs::File,
    io::{self, BufWriter, Write},
};

fn main() -> std::io::Result<()> {
    let mut args = env::args_os().skip(1);
    let text = match args.next() {
        None => false,
        Some(arg) if arg == "--txt" => true,
        Some(_) => return Err(io::Error::from(io::ErrorKind::InvalidInput)),
    };
    if args.next().is_some() {
        return Err(io::Error::from(io::ErrorKind::InvalidInput));
    }

    let table = chess::square::SliderSights::get().as_array();
    write_rust(table)?;
    if text {
        write_text(&table)?;
    }

    Ok(())
}

fn write_rust(table: &[chess::board::Bitboard; 88772]) -> io::Result<()> {
    let file = File::create("src/square/SLIDER-SIGHTS.rs")?;
    let mut writer = BufWriter::new(file);

    writeln!(writer, "// Generated by scripts/slider-sights.rs.")?;
    writeln!(writer, "SliderSights([")?;
    for sight in table {
        writeln!(writer, "    Bitboard({}),", sight.0)?;
    }
    writeln!(writer, "])")?;

    Ok(())
}

fn write_text(table: &[chess::board::Bitboard; 88772]) -> io::Result<()> {
    let file = File::create("SLIDER-SIGHTS.txt")?;
    let mut writer = BufWriter::new(file);

    for sight in table {
        writeln!(writer, "{}", sight.0)?;
    }

    Ok(())
}
