#!/usr/bin/env rust-script
//! ```cargo
//! [dependencies]
//! rustchess = { path = ".." }
//! ```

use std::{
    fs::File,
    io::{self, BufWriter, Write},
};

fn main() -> std::io::Result<()> {
    let table = chess::moves::slider_attacks();
    write_rust(&table)?;
    write_text(&table)?;

    Ok(())
}

fn write_rust(table: &[chess::bitboard::Bitboard; 88772]) -> io::Result<()> {
    let file = File::create("src/slider_attacks.rs")?;
    let mut writer = BufWriter::new(file);

    writeln!(writer, "// Generated by scripts/slider_attacks.rs.")?;
    writeln!(writer, "static SLIDER_ATTACKS: [Bitboard; 88772] = [")?;
    for attack in table {
        writeln!(writer, "    Bitboard({}),", attack.0)?;
    }
    writeln!(writer, "];")?;

    Ok(())
}

fn write_text(table: &[chess::bitboard::Bitboard; 88772]) -> io::Result<()> {
    let file = File::create("slider_attacks.txt")?;
    let mut writer = BufWriter::new(file);

    for attack in table {
        writeln!(writer, "{}", attack.0)?;
    }

    Ok(())
}
