#!/usr/bin/env rust-script
//! ```cargo
//! [dependencies]
//! rustchess = { path = "..", features = ["const-fn-statics"] }
//! ```

use std::{
    fs,
    io::{self, BufWriter, Write},
};

use chess::{
    id::{basis::Basis, Id},
    position::{
        EnPassant, EnPassantTable, File, FileTable, Player, PlayerTable, Role, RoleTable, Square,
        SquareTable,
    },
};

fn main() -> io::Result<()> {
    write_rust(Basis::generate_standard())
}

fn write_rust(basis: Basis) -> io::Result<()> {
    let file = fs::File::create("src/id/standard.rs")?;
    let mut writer = Writer::new(BufWriter::new(file));

    writer.line("// Generated by scripts/standard-id.rs.")?;
    writer.line("pub const STANDARD: Basis = Basis {")?;
    writer.indent();
    writer.field_table("board", "SquareTable", |writer| write_board(writer, basis.board))?;
    writer.field_table("turn", "PlayerTable", |writer| {
        write_player_table(writer, basis.turn, |player| format!("turn:{player}"))
    })?;
    writer.field_table("castle", "PlayerTable", |writer| write_castle(writer, basis.castle))?;
    writer.field_table("en_passant", "EnPassantTable", |writer| {
        write_en_passant(writer, basis.en_passant)
    })?;
    writer.dedent();
    writer.line("};")
}

fn write_board<W: Write>(
    writer: &mut Writer<W>,
    board: SquareTable<PlayerTable<RoleTable<Id>>>,
) -> io::Result<()> {
    writer.table_values(Square::ALL, |writer, square| {
        let players = board.get(square);
        writer.table("PlayerTable", Player::ALL, |writer, player| {
            let roles = players.get(player);
            writer.table("RoleTable", Role::ALL, |writer, role| {
                write_id(writer, &format!("board:{square}:{player}:{role}"), roles.get(role))
            })
        })
    })
}

fn write_castle<W: Write>(
    writer: &mut Writer<W>,
    castle: PlayerTable<FileTable<Id>>,
) -> io::Result<()> {
    writer.table_values(Player::ALL, |writer, player| {
        let files = castle.get(player);
        writer.table("FileTable", File::ALL, |writer, file| {
            write_id(writer, &format!("castle:{player}:{file}"), files.get(file))
        })
    })
}

fn write_en_passant<W: Write>(
    writer: &mut Writer<W>,
    en_passant: EnPassantTable<Id>,
) -> io::Result<()> {
    writer.table_values(EnPassant::ALL, |writer, square| {
        write_id(writer, &format!("en-passant:{}", square.square()), en_passant.get(square))
    })
}

fn write_player_table<W: Write>(
    writer: &mut Writer<W>,
    table: PlayerTable<Id>,
    key: impl Fn(Player) -> String,
) -> io::Result<()> {
    writer.table_values(Player::ALL, |writer, player| {
        write_id(writer, &key(player), table.get(player))
    })
}

fn write_id<W: Write>(writer: &mut Writer<W>, key: &str, id: Id) -> io::Result<()> {
    writer.line(&format!("Id({}), // {key}", hex(id.0)))
}

fn hex(value: u128) -> String {
    let hex = format!("{value:032x}");
    let mut grouped = String::with_capacity(39);
    for (index, digit) in hex.chars().enumerate() {
        if index > 0 && index % 4 == 0 {
            grouped.push('_');
        }
        grouped.push(digit);
    }
    format!("0x{grouped}")
}

struct Writer<W> {
    output: W,
    indent: usize,
}

impl<W: Write> Writer<W> {
    fn new(output: W) -> Self {
        Self { output, indent: 0 }
    }

    fn indent(&mut self) {
        self.indent += 1;
    }

    fn dedent(&mut self) {
        self.indent -= 1;
    }

    fn line(&mut self, line: &str) -> io::Result<()> {
        for _ in 0..self.indent {
            write!(self.output, "    ")?;
        }
        writeln!(self.output, "{line}")
    }

    fn field_table(
        &mut self,
        field: &str,
        name: &str,
        value: impl FnOnce(&mut Self) -> io::Result<()>,
    ) -> io::Result<()> {
        self.line(&format!("{field}: {name}::new(["))?;
        self.indent();
        value(self)?;
        self.dedent();
        self.line("]),")
    }

    fn table<T: Copy>(
        &mut self,
        name: &str,
        values: impl IntoIterator<Item = T>,
        value: impl Fn(&mut Self, T) -> io::Result<()>,
    ) -> io::Result<()> {
        self.line(&format!("{name}::new(["))?;
        self.indent();
        self.table_values(values, value)?;
        self.dedent();
        self.line("]),")
    }

    fn table_values<T: Copy>(
        &mut self,
        values: impl IntoIterator<Item = T>,
        value: impl Fn(&mut Self, T) -> io::Result<()>,
    ) -> io::Result<()> {
        for item in values {
            value(self, item)?;
        }
        Ok(())
    }
}
