// Generated by scripts/polyglot-id.rs.
// Definitive reference: https://archive.debian.org/debian/pool/main/p/polyglot/polyglot_2.0.4.orig.tar.gz
pub const POLYGLOT: Basis = Basis {
    board: SquareTable::new([
        PlayerTable::new([
            RoleTable::new([
                Id(0x9d39_247e_3377_6d41), // board:a1:black:pawn
                Id(0x5643_6c9f_e1a1_aa8d), // board:a1:black:knight
                Id(0x7f9b_6af1_ebf7_8baf), // board:a1:black:bishop
                Id(0xda3a_361b_1c51_57b1), // board:a1:black:rook
                Id(0x001f_837c_c735_0524), // board:a1:black:queen
                Id(0x230e_343d_fba0_8d33), // board:a1:black:king
            ]),
            RoleTable::new([
                Id(0x5355_f900_c2a8_2dc7), // board:a1:white:pawn
                Id(0xc547_f57e_42a7_444e), // board:a1:white:knight
                Id(0x23b7_0edb_1955_c4bf), // board:a1:white:bishop
                Id(0xa09e_8c8c_35ab_96de), // board:a1:white:rook
                Id(0x6ffe_73e8_1b63_7fb3), // board:a1:white:queen
                Id(0x55b6_344c_f97a_afae), // board:a1:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x2af7_3980_05aa_a5c7), // board:b1:black:pawn
                Id(0xefac_4b70_633b_8f81), // board:b1:black:knight
                Id(0x5862_7e1a_149b_ba21), // board:b1:black:bishop
                Id(0xdcdd_7d20_903d_0c25), // board:b1:black:rook
                Id(0x1877_b51e_57a7_64d5), // board:b1:black:queen
                Id(0x43ed_7f5a_0fae_657d), // board:b1:black:king
            ]),
            RoleTable::new([
                Id(0x07fb_9f85_5a99_7142), // board:b1:white:pawn
                Id(0x78e3_7644_e7ca_d29e), // board:b1:white:knight
                Id(0xc330_de42_6430_f69d), // board:b1:white:bishop
                Id(0xfa7e_3939_8332_5753), // board:b1:white:rook
                Id(0xddf9_57bc_36d8_b9ca), // board:b1:white:queen
                Id(0xb862_225b_055b_6960), // board:b1:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x44db_0150_2462_3547), // board:c1:black:pawn
                Id(0xbb21_5798_d45d_f7af), // board:c1:black:knight
                Id(0x2cd1_6e2a_bd79_1e33), // board:c1:black:bishop
                Id(0x3683_3336_d068_f707), // board:c1:black:rook
                Id(0xa285_3b80_f17f_58ee), // board:c1:black:queen
                Id(0x3a88_a0fb_bcb0_5c63), // board:c1:black:king
            ]),
            RoleTable::new([
                Id(0x5093_417a_a8a7_ed5e), // board:c1:white:pawn
                Id(0xfe9a_44e9_362f_05fa), // board:c1:white:knight
                Id(0x4715_ed43_e8a4_5c0a), // board:c1:white:bishop
                Id(0xd6b6_d0ec_c617_c699), // board:c1:white:rook
                Id(0x64d0_e29e_ea88_38b3), // board:c1:white:queen
                Id(0xcac0_9afb_ddd2_cdb4), // board:c1:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x9c15_f73e_62a7_6ae2), // board:d1:black:pawn
                Id(0x45f2_0042_f24f_1768), // board:d1:black:knight
                Id(0xd363_eff5_f097_7996), // board:d1:black:bishop
                Id(0xce68_341f_7989_3389), // board:d1:black:rook
                Id(0x993e_1de7_2d36_d310), // board:d1:black:queen
                Id(0x2187_4b8b_4d2d_bc4f), // board:d1:black:king
            ]),
            RoleTable::new([
                Id(0x7bcb_c38d_a25a_7f3c), // board:d1:white:pawn
                Id(0x08bd_35cc_3833_6615), // board:d1:white:knight
                Id(0xa8d7_e4da_b780_a08d), // board:d1:white:bishop
                Id(0xdfea_21ea_9e75_57e3), // board:d1:white:rook
                Id(0x08dd_9bdf_d96b_9f63), // board:d1:white:queen
                Id(0xdaf8_e982_9fe9_6b5f), // board:d1:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x7583_4465_489c_0c89), // board:e1:black:pawn
                Id(0x930f_80f4_e8eb_7462), // board:e1:black:knight
                Id(0x0ce2_a38c_344a_6eed), // board:e1:black:bishop
                Id(0xab90_9016_8dd0_5f34), // board:e1:black:rook
                Id(0xb359_8080_ce64_a656), // board:e1:black:queen
                Id(0x1bde_a12e_35f6_a8c9), // board:e1:black:king
            ]),
            RoleTable::new([
                Id(0x19fc_8a76_8cf4_b6d4), // board:e1:white:pawn
                Id(0x9315_e5eb_3a12_9ace), // board:e1:white:knight
                Id(0x0572_b974_f03c_e0bb), // board:e1:white:bishop
                Id(0xb67c_1fa4_8168_0af8), // board:e1:white:rook
                Id(0x087e_79e5_a57d_1d13), // board:e1:white:queen
                Id(0xb5fd_fc5d_3132_c498), // board:e1:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x3290_ac3a_2030_01bf), // board:f1:black:pawn
                Id(0xff67_12ff_cfd7_5ea1), // board:f1:black:knight
                Id(0x1a80_4aad_b9cf_a741), // board:f1:black:bishop
                Id(0x4395_4b32_52dc_25e5), // board:f1:black:rook
                Id(0x252f_59cf_0d9f_04bb), // board:f1:black:queen
                Id(0x53c0_65c6_c8e6_3528), // board:f1:black:king
            ]),
            RoleTable::new([
                Id(0x637a_7780_decf_c0d9), // board:f1:white:pawn
                Id(0x9406_1b87_1e04_df75), // board:f1:white:knight
                Id(0xb57d_2e98_5e14_19c7), // board:f1:white:bishop
                Id(0xca1e_3785_a9e7_24e5), // board:f1:white:rook
                Id(0xe328_e230_e3e2_b3fb), // board:f1:white:queen
                Id(0x310c_b380_db6f_7503), // board:f1:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x0fbb_ad1f_6104_2279), // board:g1:black:pawn
                Id(0xae62_3fd6_7468_aa70), // board:g1:black:knight
                Id(0x907f_3042_1d78_c5de), // board:g1:black:bishop
                Id(0xb438_c2b6_7f98_e5e9), // board:g1:black:rook
                Id(0xd23c_8e17_6d11_3600), // board:g1:black:queen
                Id(0xe34a_1d25_0e7a_8d6b), // board:g1:black:king
            ]),
            RoleTable::new([
                Id(0x8249_a47a_ee0e_41f7), // board:g1:white:pawn
                Id(0xdf1d_9f9d_784b_a010), // board:g1:white:knight
                Id(0xe8d9_ecbe_2cf3_d73f), // board:g1:white:bishop
                Id(0x1cfc_8bed_0d68_1639), // board:g1:white:rook
                Id(0x1c25_59e3_0f09_46be), // board:g1:white:queen
                Id(0xe87f_bb46_217a_360e), // board:g1:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xe83a_908f_f2fb_60ca), // board:h1:black:pawn
                Id(0xdd2c_5bc8_4bc8_d8fc), // board:h1:black:knight
                Id(0x501f_65ed_b303_4d07), // board:h1:black:bishop
                Id(0x10dc_d78e_3851_a492), // board:h1:black:rook
                Id(0x1bda_0492_e7e4_586e), // board:h1:black:queen
                Id(0xd6b0_4d3b_7651_dd7e), // board:h1:black:king
            ]),
            RoleTable::new([
                Id(0x79ad_6955_01e7_d1e8), // board:h1:white:pawn
                Id(0x3bba_57b6_8871_b59d), // board:h1:white:knight
                Id(0x2fe4_b171_70e5_9750), // board:h1:white:bishop
                Id(0xd18d_8549_d140_caea), // board:h1:white:rook
                Id(0x720b_f5f2_6f4d_2eaa), // board:h1:white:queen
                Id(0x2102_ae46_6ebb_1148), // board:h1:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x0d7e_765d_5875_5c10), // board:a2:black:pawn
                Id(0x7eed_120d_54cf_2dd9), // board:a2:black:knight
                Id(0x3762_4ae5_a48f_a6e9), // board:a2:black:bishop
                Id(0xdbc2_7ab5_4478_22bf), // board:a2:black:rook
                Id(0x21e0_bd50_26c6_19bf), // board:a2:black:queen
                Id(0x5e90_277e_7cb3_9e2d), // board:a2:black:king
            ]),
            RoleTable::new([
                Id(0x14ac_baf4_777d_5776), // board:a2:white:pawn
                Id(0xd2b7_adee_ded1_f73f), // board:a2:white:knight
                Id(0x1131_7ba8_7905_e790), // board:a2:white:bishop
                Id(0x4ed0_fe7e_9dc9_1335), // board:a2:white:rook
                Id(0xb077_4d26_1cc6_09db), // board:a2:white:queen
                Id(0xf854_9e1a_3aa5_e00d), // board:a2:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x1a08_3822_ceaf_e02d), // board:b2:black:pawn
                Id(0x22fe_5454_0116_5f1c), // board:b2:black:knight
                Id(0x957b_af61_700c_ff4e), // board:b2:black:bishop
                Id(0x9b3c_db65_f82c_a382), // board:b2:black:rook
                Id(0x3b09_7ada_f088_f94e), // board:b2:black:queen
                Id(0x2c04_6f22_062d_c67d), // board:b2:black:king
            ]),
            RoleTable::new([
                Id(0xf145_b6be_ccde_a195), // board:b2:white:pawn
                Id(0xf7a2_55d8_3bc3_73f8), // board:b2:white:knight
                Id(0x7fbf_21ec_8a1f_45ec), // board:b2:white:bishop
                Id(0xe4db_f063_4473_f5d2), // board:b2:white:rook
                Id(0x443f_64ec_5a37_1195), // board:b2:white:queen
                Id(0x07a6_9afd_cc42_261a), // board:b2:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x9605_d5f0_e25e_c3b0), // board:c2:black:pawn
                Id(0xc918_00e9_8fb9_9929), // board:c2:black:knight
                Id(0x3a6c_2793_4e31_188a), // board:c2:black:bishop
                Id(0xb67b_7896_167b_4c84), // board:c2:black:rook
                Id(0x8d14_dedb_30be_846e), // board:c2:black:queen
                Id(0xb10b_b459_132d_0a26), // board:c2:black:king
            ]),
            RoleTable::new([
                Id(0xdabf_2ac8_2017_52fc), // board:c2:white:pawn
                Id(0xd7f4_f244_8c0c_eb81), // board:c2:white:knight
                Id(0x1725_cabf_cb04_5b00), // board:c2:white:bishop
                Id(0x1761_f93a_44d5_aefe), // board:c2:white:rook
                Id(0x4112_cf68_649a_260e), // board:c2:white:queen
                Id(0xc4c1_18bf_e78f_eaae), // board:c2:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xd021_ff5c_d13a_2ed5), // board:d2:black:pawn
                Id(0x808b_d68e_6ac1_0365), // board:d2:black:knight
                Id(0xd495_0353_6abc_a345), // board:d2:black:bishop
                Id(0xbfce_d1b0_048e_ac50), // board:d2:black:rook
                Id(0xf95c_ffa2_3af5_f6f4), // board:d2:black:queen
                Id(0x3fa9_ddfb_67e2_f199), // board:d2:black:king
            ]),
            RoleTable::new([
                Id(0x24c3_c94d_f9c8_d3f6), // board:d2:white:pawn
                Id(0xd95b_e88c_d210_ffa7), // board:d2:white:knight
                Id(0x964e_915c_d5e2_b207), // board:d2:white:bishop
                Id(0x5389_8e4c_3910_da55), // board:d2:white:rook
                Id(0xd813_f2fa_b7f5_c5ca), // board:d2:white:queen
                Id(0xf9f4_892e_d96b_d438), // board:d2:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x40bd_f15d_4a67_2e32), // board:e2:black:pawn
                Id(0xdec4_6814_5b76_05f6), // board:e2:black:knight
                Id(0x088e_0495_89c4_32e0), // board:e2:black:bishop
                Id(0xa911_9b60_369f_febd), // board:e2:black:rook
                Id(0x3871_7007_61b3_f743), // board:e2:black:queen
                Id(0x0e09_b88e_1914_f7af), // board:e2:black:king
            ]),
            RoleTable::new([
                Id(0xbb6e_2924_f039_12ea), // board:e2:white:pawn
                Id(0x336f_52f8_ff47_28e7), // board:e2:white:knight
                Id(0x3e2b_8bcb_f016_d66d), // board:e2:white:bishop
                Id(0x734d_e818_1f6e_c39a), // board:e2:white:rook
                Id(0x660d_3257_3808_41ee), // board:e2:white:queen
                Id(0x1af3_dbe2_5d8f_45da), // board:e2:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x0113_5514_6fd5_6395), // board:f2:black:pawn
                Id(0x1bed_e3a3_aef5_3302), // board:f2:black:knight
                Id(0xf943_aee7_febf_21b8), // board:f2:black:bishop
                Id(0x1fff_7ac8_0904_bf45), // board:f2:black:rook
                Id(0xca67_2b91_e9e4_fa16), // board:f2:black:queen
                Id(0x10e8_b35a_f3ee_ab37), // board:f2:black:king
            ]),
            RoleTable::new([
                Id(0x0ce2_6c0b_95c9_80d9), // board:f2:white:pawn
                Id(0xa740_49da_c312_ac71), // board:f2:white:knight
                Id(0xbe74_44e3_9328_a0ac), // board:f2:white:bishop
                Id(0x2680_b122_baa2_8d97), // board:f2:white:rook
                Id(0x59ac_2c78_73f9_10a3), // board:f2:white:queen
                Id(0xf5b4_b0b0_d2de_eeb4), // board:f2:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x5db4_8320_46f3_d9e5), // board:g2:black:pawn
                Id(0x4353_9603_d6c5_5602), // board:g2:black:knight
                Id(0x6c3b_8e3e_3361_39d3), // board:g2:black:bishop
                Id(0xac12_fb17_1817_eee7), // board:g2:black:rook
                Id(0x64c8_e531_bff5_3b55), // board:g2:black:queen
                Id(0x9eed_eca8_e272_b933), // board:g2:black:king
            ]),
            RoleTable::new([
                Id(0xa49c_d132_bfbf_7cc4), // board:g2:white:pawn
                Id(0xa2f6_1bb6_e437_fdb5), // board:g2:white:knight
                Id(0xf85b_2b4f_bcde_44b7), // board:g2:white:bishop
                Id(0x298a_f231_c85b_afab), // board:g2:white:rook
                Id(0xe846_9638_7767_1a17), // board:g2:white:queen
                Id(0x962a_ceef_a82e_1c84), // board:g2:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x239f_8b2d_7ff7_19cc), // board:h2:black:pawn
                Id(0xaa96_9b5c_691c_cb7a), // board:h2:black:knight
                Id(0x364f_6ffa_464e_e52e), // board:h2:black:bishop
                Id(0xaf08_da91_77dd_a93d), // board:h2:black:rook
                Id(0x2412_60ed_4ad1_e87d), // board:h2:black:queen
                Id(0xd4c7_18bc_4ae8_ae5f), // board:h2:black:king
            ]),
            RoleTable::new([
                Id(0xe99d_662a_f424_3939), // board:h2:white:pawn
                Id(0x4f2a_5cb0_7f6a_35b3), // board:h2:white:knight
                Id(0x4935_3fea_39ba_63b1), // board:h2:white:bishop
                Id(0x7983_eed3_7408_47d5), // board:h2:white:rook
                Id(0x93b6_33ab_fa34_69f8), // board:h2:white:queen
                Id(0x046e_3eca_af45_3ce9), // board:h2:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x05d1_a1ae_85b4_9aa1), // board:a3:black:pawn
                Id(0xa878_32d3_92ef_ee56), // board:a3:black:knight
                Id(0xd60f_6dce_dc31_4222), // board:a3:black:bishop
                Id(0x1b0c_ab93_6e65_c744), // board:a3:black:rook
                Id(0x106c_09b9_72d2_e822), // board:a3:black:queen
                Id(0x8153_6d60_1170_fc20), // board:a3:black:king
            ]),
            RoleTable::new([
                Id(0x27e6_ad78_9116_5c3f), // board:a3:white:pawn
                Id(0x87d3_80bd_a5bf_7859), // board:a3:white:knight
                Id(0x1dd0_1aaf_cd53_486a), // board:a3:white:bishop
                Id(0x66c1_a2a1_a60c_d889), // board:a3:white:rook
                Id(0xc0c0_f5a6_0ef4_cdcf), // board:a3:white:queen
                Id(0xf05d_1296_8194_9a4c), // board:a3:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x679f_848f_6e8f_c971), // board:b3:black:pawn
                Id(0x6594_2c7b_3c7e_11ae), // board:b3:black:knight
                Id(0x5696_3b0d_ca41_8fc0), // board:b3:black:bishop
                Id(0xb559_eb1d_04e5_e932), // board:b3:black:rook
                Id(0x7fba_1954_10e5_ca30), // board:b3:black:queen
                Id(0x91b5_34f8_8581_8a06), // board:b3:black:king
            ]),
            RoleTable::new([
                Id(0x8535_f040_b974_4ff1), // board:b3:white:pawn
                Id(0x16b9_f7e0_6c45_3a21), // board:b3:white:knight
                Id(0x1fca_8a92_fd71_9f85), // board:b3:white:bishop
                Id(0x9e17_e496_42a3_e4c1), // board:b3:white:rook
                Id(0xcaf2_1ecd_4377_b28c), // board:b3:white:queen
                Id(0x9647_81ce_734b_3c84), // board:b3:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x7449_bbff_801f_ed0b), // board:c3:black:pawn
                Id(0xded2_d633_cad0_04f6), // board:c3:black:knight
                Id(0x16f5_0edf_91e5_13af), // board:c3:black:bishop
                Id(0xc37b_45b3_f8d6_f2ba), // board:c3:black:rook
                Id(0x7884_d9bc_6cb5_69d8), // board:c3:black:queen
                Id(0xec81_77f8_3f90_0978), // board:c3:black:king
            ]),
            RoleTable::new([
                Id(0x54b3_f4fa_5f40_d873), // board:c3:white:pawn
                Id(0x7ba2_484c_8a0f_d54e), // board:c3:white:knight
                Id(0xfc7c_95d8_2735_7afa), // board:c3:white:bishop
                Id(0xedb4_54e7_badc_0805), // board:c3:white:rook
                Id(0x5727_7707_199b_8175), // board:c3:white:queen
                Id(0x9c2e_d440_81ce_5fbd), // board:c3:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x7d11_cdb1_c3b7_adf0), // board:d3:black:pawn
                Id(0x21f0_8570_f420_e565), // board:d3:black:knight
                Id(0xef19_5591_4b60_9f93), // board:d3:black:bishop
                Id(0xc3a9_dc22_8caa_c9e9), // board:d3:black:rook
                Id(0x0647_dfed_cd89_4a29), // board:d3:black:queen
                Id(0x190e_714f_ada5_156e), // board:d3:black:king
            ]),
            RoleTable::new([
                Id(0x72b1_2c32_127f_ed2b), // board:d3:white:pawn
                Id(0xf3a6_78ca_d9a2_e38c), // board:d3:white:knight
                Id(0x18a6_a990_c8b3_5ebd), // board:d3:white:bishop
                Id(0x50b7_04ca_b602_c329), // board:d3:white:rook
                Id(0x506c_11b9_d90e_8b1d), // board:d3:white:queen
                Id(0x522e_23f3_925e_319e), // board:d3:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x82c7_709e_781e_b7cc), // board:e3:black:pawn
                Id(0xb415_938d_7da9_4e3c), // board:e3:black:knight
                Id(0x5656_01c0_364e_3228), // board:e3:black:bishop
                Id(0xf3b8_b667_5a65_07ff), // board:e3:black:rook
                Id(0x6357_3ff0_3e22_4774), // board:e3:black:queen
                Id(0xb592_bf39_b036_4963), // board:e3:black:king
            ]),
            RoleTable::new([
                Id(0xee95_4d3c_7b41_1f47), // board:e3:white:pawn
                Id(0x39b0_bf7d_de43_7ba2), // board:e3:white:knight
                Id(0xcccb_7005_c6b9_c28d), // board:e3:white:bishop
                Id(0x4cc3_17fb_9cdd_d023), // board:e3:white:rook
                Id(0xd83c_c268_7a19_255f), // board:e3:white:queen
                Id(0x177e_00f9_fc32_f791), // board:e3:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xf321_8f1c_9510_786c), // board:f3:black:pawn
                Id(0x91b8_59e5_9ecb_6350), // board:f3:black:knight
                Id(0xecb5_3939_887e_8175), // board:f3:black:bishop
                Id(0x9fc4_77de_4ed6_81da), // board:f3:black:rook
                Id(0x4fc8_e956_0f91_b123), // board:f3:black:queen
                Id(0x89c3_50c8_93ae_7dc1), // board:f3:black:king
            ]),
            RoleTable::new([
                Id(0x9a85_ac90_9a24_eaa1), // board:f3:white:pawn
                Id(0xfcaf_55c1_bf8a_4424), // board:f3:white:knight
                Id(0x3bdb_b92c_43b1_7f26), // board:f3:white:bishop
                Id(0x66b4_835d_9eaf_ea22), // board:f3:white:rook
                Id(0x4a29_c646_5a31_4cd1), // board:f3:white:queen
                Id(0x2bc6_0a63_a6f3_b3f2), // board:f3:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x3314_78f3_af51_bbe6), // board:g3:black:pawn
                Id(0x10cf_f333_e0ed_804a), // board:g3:black:knight
                Id(0xbac7_a9a1_8531_294b), // board:g3:black:bishop
                Id(0x6737_8d8e_ccef_96cb), // board:g3:black:rook
                Id(0x1db9_56e4_5027_5779), // board:g3:black:queen
                Id(0xac04_2e70_f8b3_83f2), // board:g3:black:king
            ]),
            RoleTable::new([
                Id(0x70ac_4cd9_f04f_21f5), // board:g3:white:pawn
                Id(0x18fc_f680_573f_a594), // board:g3:white:knight
                Id(0xaa70_b5b4_f896_95a2), // board:g3:white:bishop
                Id(0x219b_97e2_6ffc_81bd), // board:g3:white:rook
                Id(0xed2d_f212_1623_5097), // board:g3:white:queen
                Id(0x222b_bfae_6172_5606), // board:g3:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x4bb3_8de5_e721_9443), // board:h3:black:pawn
                Id(0x28ae_d140_be0b_b7dd), // board:h3:black:knight
                Id(0xb344_c470_397b_ba52), // board:h3:black:bishop
                Id(0x6dd8_56d9_4d25_9236), // board:h3:black:rook
                Id(0xb8d9_1274_b9e9_d4fb), // board:h3:black:queen
                Id(0xb49b_52e5_87a1_ee60), // board:h3:black:king
            ]),
            RoleTable::new([
                Id(0xf9b8_9d3e_99a0_75c2), // board:h3:white:pawn
                Id(0x4c05_63b8_9f49_5ac3), // board:h3:white:knight
                Id(0xe94c_39a5_4a98_307f), // board:h3:white:bishop
                Id(0x261e_4e4c_0a33_3a9d), // board:h3:white:rook
                Id(0xb563_5c95_ff72_96e2), // board:h3:white:queen
                Id(0x4862_89dd_cc3d_6780), // board:h3:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xaa64_9c6e_bcfd_50fc), // board:a4:black:pawn
                Id(0xc5cc_1d89_724f_a456), // board:a4:black:knight
                Id(0x65d3_4954_daf3_cebd), // board:a4:black:bishop
                Id(0xa319_ce15_b0b4_db31), // board:a4:black:rook
                Id(0xa2eb_ee47_e2fb_fce1), // board:a4:black:queen
                Id(0xfb15_2fe3_ff26_da89), // board:a4:black:king
            ]),
            RoleTable::new([
                Id(0x87b3_e2b2_b5c9_07b1), // board:a4:white:pawn
                Id(0x40e0_8793_1a00_930d), // board:a4:white:knight
                Id(0xb7a0_b174_cff6_f36e), // board:a4:white:bishop
                Id(0x1fe2_cca7_6517_db90), // board:a4:white:rook
                Id(0x22af_003a_b672_e811), // board:a4:white:queen
                Id(0x7dc7_785b_8efd_fc80), // board:a4:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x8dbd_98a3_52af_d40b), // board:b4:black:pawn
                Id(0x5648_f680_f11a_2741), // board:b4:black:knight
                Id(0xb4b8_1b3f_a975_11e2), // board:b4:black:bishop
                Id(0x0739_7375_1f12_dd5e), // board:b4:black:rook
                Id(0xd9f1_f30c_cd97_fb09), // board:b4:black:queen
                Id(0x3e66_6e6f_69ae_2c15), // board:b4:black:king
            ]),
            RoleTable::new([
                Id(0xa366_e5b8_c54f_48b8), // board:b4:white:pawn
                Id(0x8cff_a941_2eb6_42c1), // board:b4:white:knight
                Id(0xd4db_a847_29af_48ad), // board:b4:white:bishop
                Id(0xd750_4dfa_8816_edbb), // board:b4:white:rook
                Id(0x52e7_6259_6bf6_8235), // board:b4:white:queen
                Id(0x8af3_8731_c02b_a980), // board:b4:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x87d2_074b_81d7_9217), // board:c4:black:pawn
                Id(0x2d25_5069_f0b7_dab3), // board:c4:black:knight
                Id(0xb422_0611_93d6_f6a7), // board:c4:black:bishop
                Id(0x8a8e_849e_b327_81a5), // board:c4:black:rook
                Id(0xefed_53d7_5fd6_4e6b), // board:c4:black:queen
                Id(0x3b54_4ebe_544c_19f9), // board:c4:black:king
            ]),
            RoleTable::new([
                Id(0xae4a_9346_cc3f_7cf2), // board:c4:white:pawn
                Id(0x68ca_3905_3261_169f), // board:c4:white:knight
                Id(0x2e18_bc1a_d970_4a68), // board:c4:white:bishop
                Id(0xb957_1fa0_4dc0_89c8), // board:c4:white:rook
                Id(0x9aeb_a33a_c6ec_c6b0), // board:c4:white:queen
                Id(0x1fab_64ea_29a2_ddf7), // board:c4:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x19f3_c751_d3e9_2ae1), // board:d4:black:pawn
                Id(0x9bc5_a38e_f729_abd4), // board:d4:black:knight
                Id(0x0715_8240_1c38_434d), // board:d4:black:bishop
                Id(0xe192_5c71_2852_79f5), // board:d4:black:rook
                Id(0x2e6d_02c3_6017_f67f), // board:d4:black:queen
                Id(0xe805_a1e2_90cf_2456), // board:d4:black:king
            ]),
            RoleTable::new([
                Id(0x1920_c04d_4726_7bbd), // board:d4:white:pawn
                Id(0x7a1e_e967_d275_79e2), // board:d4:white:knight
                Id(0x2de0_966d_af2f_8b1c), // board:d4:white:bishop
                Id(0x1ddc_0325_259b_27de), // board:d4:white:rook
                Id(0x944f_6de0_9134_dfb6), // board:d4:white:queen
                Id(0xe4d9_4293_22cd_065a), // board:d4:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xb4ab_30f0_62b1_9abf), // board:e4:black:pawn
                Id(0xef2f_0543_08f6_a2bc), // board:e4:black:knight
                Id(0x7a13_f18b_bedc_4ff5), // board:e4:black:bishop
                Id(0x74c0_4bf1_790c_0efe), // board:e4:black:rook
                Id(0xa9aa_4d20_db08_4e9b), // board:e4:black:queen
                Id(0x24b3_3c9d_7ed2_5117), // board:e4:black:king
            ]),
            RoleTable::new([
                Id(0x87bf_02c6_b49e_2ae9), // board:e4:white:pawn
                Id(0x9d1d_60e5_076f_5b6f), // board:e4:white:knight
                Id(0xb9c1_1d5b_1e43_a07e), // board:e4:white:bishop
                Id(0xcf3f_4688_801e_b9aa), // board:e4:white:rook
                Id(0x6c47_bec8_83a7_de39), // board:e4:white:queen
                Id(0x9da0_58c6_7844_f20c), // board:e4:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x7b05_00ac_4204_7ac4), // board:f4:black:pawn
                Id(0xaf20_42f5_cc5c_2858), // board:f4:black:knight
                Id(0xbc40_97b1_16c5_24d2), // board:f4:black:bishop
                Id(0x4dda_4815_3c94_938a), // board:f4:black:rook
                Id(0xb64b_e8d8_b253_96c1), // board:f4:black:queen
                Id(0xe747_3342_7b72_f0c1), // board:f4:black:king
            ]),
            RoleTable::new([
                Id(0x0922_37ac_237f_3859), // board:f4:white:pawn
                Id(0x3810_e399_b6f6_5ba2), // board:f4:white:knight
                Id(0x6497_2d68_dee3_3360), // board:f4:white:bishop
                Id(0xf4f5_d05c_10ca_b243), // board:f4:white:rook
                Id(0x6ad0_47c4_30a1_2104), // board:f4:white:queen
                Id(0x24c0_e332_b700_19b0), // board:f4:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xc945_2ca8_1a09_d85d), // board:g4:black:pawn
                Id(0x4804_12ba_b7f5_be2a), // board:g4:black:knight
                Id(0x59b9_7885_e2f2_ea28), // board:g4:black:bishop
                Id(0x9d26_6d6a_1cc0_542c), // board:g4:black:rook
                Id(0x70cb_6af7_c2d5_bcf0), // board:g4:black:queen
                Id(0x0a80_4d18_b709_7475), // board:g4:black:king
            ]),
            RoleTable::new([
                Id(0xff07_f64e_f8ed_14d0), // board:g4:white:pawn
                Id(0x3209_5b6d_4ab5_f9b1), // board:g4:white:knight
                Id(0x9462_8d38_d0c2_0584), // board:g4:white:bishop
                Id(0x38b6_525c_21a4_2b0e), // board:g4:white:rook
                Id(0xa5b1_cfdb_a0ab_4067), // board:g4:white:queen
                Id(0x2330_03b5_a6cf_e6ad), // board:g4:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x24aa_6c51_4da2_7500), // board:h4:black:pawn
                Id(0xaef3_af4a_563d_fe43), // board:h4:black:knight
                Id(0x9917_0a5d_c311_5544), // board:h4:black:bishop
                Id(0x7440_fb81_6508_c4fe), // board:h4:black:rook
                Id(0x98f0_76a4_f7a2_322e), // board:h4:black:queen
                Id(0x57e3_306d_881e_db4f), // board:h4:black:king
            ]),
            RoleTable::new([
                Id(0x8de8_dca9_f03c_c54e), // board:h4:white:pawn
                Id(0x35ca_b621_09dd_038a), // board:h4:white:knight
                Id(0xdbc0_d2b6_ab90_a559), // board:h4:white:bishop
                Id(0x36f6_0e2b_a4fa_6800), // board:h4:white:rook
                Id(0x7c45_d833_aff0_7862), // board:h4:white:queen
                Id(0xd586_bd01_c5c2_17f6), // board:h4:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x4c9f_3442_7501_b447), // board:a5:black:pawn
                Id(0x19af_e59a_e451_497f), // board:a5:black:knight
                Id(0x6f42_3357_e7c6_a9f9), // board:a5:black:bishop
                Id(0x1332_8503_df48_229f), // board:a5:black:rook
                Id(0xbf84_4708_05e6_9b5f), // board:a5:black:queen
                Id(0x4ae7_d6a3_6eb5_dbcb), // board:a5:black:king
            ]),
            RoleTable::new([
                Id(0x9c16_3326_4db4_9c89), // board:a5:white:pawn
                Id(0xa90b_2449_9fcf_afb1), // board:a5:white:knight
                Id(0xd273_3c43_35c6_a72f), // board:a5:white:bishop
                Id(0xeb35_9380_3173_e0ce), // board:a5:white:rook
                Id(0x5092_ef95_0a16_da0b), // board:a5:white:queen
                Id(0x5e56_3788_5f29_bc2b), // board:a5:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x14a6_8fd7_3c91_0841), // board:b5:black:pawn
                Id(0x5259_3803_dff1_e840), // board:b5:black:knight
                Id(0x3259_28ee_6e6f_8794), // board:b5:black:bishop
                Id(0xd6bf_7bae_e43c_ac40), // board:b5:black:rook
                Id(0x94c3_251f_06f9_0cf3), // board:b5:black:queen
                Id(0x2d8d_5432_1570_64c8), // board:b5:black:king
            ]),
            RoleTable::new([
                Id(0xb3f2_2c3d_0b0b_38ed), // board:b5:white:pawn
                Id(0x77a2_25a0_7cc2_c6bd), // board:b5:white:knight
                Id(0x7e75_d99d_94a7_0f4d), // board:b5:white:bishop
                Id(0x9c4c_d625_7c5a_3603), // board:b5:white:rook
                Id(0x9338_e69c_052b_8e7b), // board:b5:white:queen
                Id(0x7eba_726d_8c94_094b), // board:b5:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xa71b_9b83_461c_bd93), // board:c5:black:pawn
                Id(0xf4f0_76e6_5f2c_e6f0), // board:c5:black:knight
                Id(0xd0e4_3662_28b0_3343), // board:c5:black:bishop
                Id(0x4838_d65f_6ef6_748f), // board:c5:black:rook
                Id(0x3e00_3e61_6a65_91e9), // board:c5:black:queen
                Id(0xd1e6_49de_1e7f_268b), // board:c5:black:king
            ]),
            RoleTable::new([
                Id(0x390e_5fb4_4d01_144b), // board:c5:white:pawn
                Id(0x513e_5e63_4c70_e331), // board:c5:white:knight
                Id(0x6ced_1983_376f_a72b), // board:c5:white:bishop
                Id(0xaf0c_317d_32ad_aa8a), // board:c5:white:rook
                Id(0x455a_4b4c_fe30_e3f5), // board:c5:white:queen
                Id(0x0a56_a5f0_bfe3_9272), // board:c5:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x0348_8b95_b0f1_850f), // board:d5:black:pawn
                Id(0x1137_9625_747d_5af3), // board:d5:black:knight
                Id(0x565c_31f7_de89_ea27), // board:d5:black:bishop
                Id(0x1e15_2328_f331_8dea), // board:d5:black:rook
                Id(0xb925_a6cd_0421_aff3), // board:d5:black:queen
                Id(0x8a32_8a1c_edfe_552c), // board:d5:black:king
            ]),
            RoleTable::new([
                Id(0x5bfe_a5b4_7127_68e9), // board:d5:white:pawn
                Id(0x4361_c0ca_3f69_2f12), // board:d5:white:knight
                Id(0x97fc_aacb_f030_bc24), // board:d5:white:bishop
                Id(0x258e_5a80_c720_4c4b), // board:d5:white:rook
                Id(0x6b02_e631_95ad_0cf8), // board:d5:white:queen
                Id(0xd794_76a8_4ee2_0d06), // board:d5:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x637b_2b34_ff93_c040), // board:e5:black:pawn
                Id(0xbce5_d224_8682_c115), // board:e5:black:knight
                Id(0x30f5_6114_8411_9414), // board:e5:black:bishop
                Id(0x8f84_19a3_48f2_96bf), // board:e5:black:rook
                Id(0x61bd_d130_7c66_e300), // board:e5:black:queen
                Id(0x07a3_aec7_9624_c7da), // board:e5:black:king
            ]),
            RoleTable::new([
                Id(0x1e10_3291_1fa7_8984), // board:e5:white:pawn
                Id(0xd941_aca4_4b20_a45b), // board:e5:white:knight
                Id(0x7b77_497b_3250_3b12), // board:e5:white:bishop
                Id(0x8b88_9d62_4d44_885d), // board:e5:white:rook
                Id(0x6b17_b224_bad6_bf27), // board:e5:white:queen
                Id(0x9e4c_1269_baa4_bf37), // board:e5:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x09d1_bc9a_3dd9_0a94), // board:f5:black:pawn
                Id(0x9da4_243d_e836_994f), // board:f5:black:knight
                Id(0xd873_db39_1292_ed4f), // board:f5:black:bishop
                Id(0x72c8_834a_5957_b511), // board:f5:black:rook
                Id(0xbf8d_5108_e27e_0d48), // board:f5:black:queen
                Id(0x8454_7ddc_3e20_3c94), // board:f5:black:king
            ]),
            RoleTable::new([
                Id(0x9a74_acb9_64e7_8cb3), // board:f5:white:pawn
                Id(0x528f_7c86_02c5_807b), // board:f5:white:knight
                Id(0x8547_eddf_b81c_cb94), // board:f5:white:bishop
                Id(0xf4d1_4597_e660_f855), // board:f5:white:rook
                Id(0xd1e0_ccd2_5bb9_c169), // board:f5:white:queen
                Id(0x17ef_ee45_b0de_e640), // board:f5:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x3575_6683_34a1_dd3b), // board:g5:black:pawn
                Id(0x066f_70b3_3fe0_9017), // board:g5:black:knight
                Id(0x7bd9_4e1d_8e17_debc), // board:g5:black:bishop
                Id(0xd7a0_23a7_3260_b45c), // board:g5:black:rook
                Id(0x240a_b57a_8b88_8b20), // board:g5:black:queen
                Id(0x990a_98fd_5071_d263), // board:g5:black:king
            ]),
            RoleTable::new([
                Id(0x4f80_f7a0_35da_fb04), // board:g5:white:pawn
                Id(0x52ab_92be_b961_3989), // board:g5:white:knight
                Id(0x7999_9cdf_f709_02cb), // board:g5:white:bishop
                Id(0xd434_7f66_ec89_41c3), // board:g5:white:rook
                Id(0xde0c_89a5_56b9_ae70), // board:g5:white:queen
                Id(0x1d95_b0a5_fcf9_0bc6), // board:g5:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x735e_2b97_a4c4_5a23), // board:h5:black:pawn
                Id(0x4dc4_de18_9b67_1a1c), // board:h5:black:knight
                Id(0xc7d9_f168_64a7_6e94), // board:h5:black:bishop
                Id(0x94eb_c8ab_cfb5_6dae), // board:h5:black:rook
                Id(0xfc87_614b_af28_7e07), // board:h5:black:queen
                Id(0x1a4f_f126_16ee_fc89), // board:h5:black:king
            ]),
            RoleTable::new([
                Id(0x6304_d09a_0b37_38c4), // board:h5:white:pawn
                Id(0x9d1d_fa2e_fc55_7f73), // board:h5:white:knight
                Id(0xcffe_1939_438e_9b24), // board:h5:white:bishop
                Id(0xe699_ed85_b0df_b40d), // board:h5:white:rook
                Id(0x5006_5e53_5a21_3cf6), // board:h5:white:queen
                Id(0x93cb_e0b6_99c2_585d), // board:h5:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x1872_7070_f1bd_400b), // board:a6:black:pawn
                Id(0x5103_9ab7_7124_57c3), // board:a6:black:knight
                Id(0x947a_e053_ee56_e63c), // board:a6:black:bishop
                Id(0x9fc1_0d0f_9899_93e0), // board:a6:black:rook
                Id(0xef02_cdd0_6ffd_b432), // board:a6:black:queen
                Id(0xf6f7_fd14_3171_4200), // board:a6:black:king
            ]),
            RoleTable::new([
                Id(0x2171_e646_8302_3a08), // board:a6:white:pawn
                Id(0x722f_f175_f572_c348), // board:a6:white:knight
                Id(0x8296_26e3_892d_95d7), // board:a6:white:bishop
                Id(0x2472_f620_7c2d_0484), // board:a6:white:rook
                Id(0x9c11_69fa_2777_b874), // board:a6:white:queen
                Id(0x65fa_4f22_7a2b_6d79), // board:a6:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x1fcb_acd2_59bf_02e7), // board:b6:black:pawn
                Id(0xc07a_3f80_c31f_b4b4), // board:b6:black:knight
                Id(0xc8c9_3882_f947_5f5f), // board:b6:black:bishop
                Id(0xde68_a235_5b93_cae6), // board:b6:black:rook
                Id(0xa108_2c04_66df_6c0a), // board:b6:black:queen
                Id(0x30c0_5b1b_a332_f41c), // board:b6:black:king
            ]),
            RoleTable::new([
                Id(0x5b9b_63eb_9cef_f80c), // board:b6:white:pawn
                Id(0x1d12_60a5_1107_fe97), // board:b6:white:knight
                Id(0x92fa_e242_91f2_b3f1), // board:b6:white:bishop
                Id(0xc2a1_e7b5_b459_aeb5), // board:b6:white:rook
                Id(0x78ed_efd6_94af_1eed), // board:b6:white:queen
                Id(0xd5f9_e858_2925_04d5), // board:b6:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xd310_a7c2_ce9b_6555), // board:c6:black:pawn
                Id(0xb46e_e9c5_e64a_6e7c), // board:c6:black:knight
                Id(0x3a9b_f55b_a91f_81ca), // board:c6:black:bishop
                Id(0xa44c_fe79_ae53_8bbe), // board:c6:black:rook
                Id(0x8215_e577_0013_32c8), // board:c6:black:queen
                Id(0x8d26_36b8_1555_a786), // board:c6:black:king
            ]),
            RoleTable::new([
                Id(0x506a_acf4_8988_9342), // board:c6:white:pawn
                Id(0x7a24_9a57_ec0c_9ba2), // board:c6:white:knight
                Id(0x63e2_2c14_7b9c_3403), // board:c6:white:bishop
                Id(0xab4f_6451_cc1d_45ec), // board:c6:white:rook
                Id(0x6dc9_3d95_26a5_0e68), // board:c6:white:queen
                Id(0xc2b5_a03f_7147_1a6f), // board:c6:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xbf98_3fe0_fe5d_8244), // board:d6:black:pawn
                Id(0xb381_9a42_abe6_1c87), // board:d6:black:knight
                Id(0xd9a1_1fbb_3d98_08e4), // board:d6:black:bishop
                Id(0x9d1d_84fc_ce37_1425), // board:d6:black:rook
                Id(0xd39b_b9c3_a48d_b6cf), // board:d6:black:queen
                Id(0x46c9_feb5_5d12_0902), // board:d6:black:king
            ]),
            RoleTable::new([
                Id(0x1881_afc9_a3a7_01d6), // board:d6:white:pawn
                Id(0x0420_8fe9_e8f7_f2d6), // board:d6:white:knight
                Id(0xc678_b6d8_6028_4a1c), // board:d6:white:bishop
                Id(0x6376_7572_ae3d_6174), // board:d6:white:rook
                Id(0xee97_f453_f067_91ed), // board:d6:white:queen
                Id(0x5930_0222_b456_1e00), // board:d6:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x9f74_d14f_7454_a824), // board:e6:black:pawn
                Id(0x21a0_0793_3a52_2a20), // board:e6:black:knight
                Id(0x0fd2_2063_edc2_9fca), // board:e6:black:bishop
                Id(0x51d2_b1ab_2ddf_b636), // board:e6:black:rook
                Id(0x2738_2596_3430_5c14), // board:e6:black:queen
                Id(0xccec_0a73_b49c_9921), // board:e6:black:king
            ]),
            RoleTable::new([
                Id(0x6503_0804_4075_0644), // board:e6:white:pawn
                Id(0x5a11_0c60_58b9_20a0), // board:e6:white:knight
                Id(0x5873_8888_5065_9ae7), // board:e6:white:bishop
                Id(0xa59e_0bd1_0173_1a28), // board:e6:white:rook
                Id(0x32ab_0edb_6967_03d3), // board:e6:white:queen
                Id(0xce2f_8642_ca07_12dc), // board:e6:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x51eb_dc4a_b9ba_3035), // board:f6:black:pawn
                Id(0x2df1_6f76_1598_aa4f), // board:f6:black:knight
                Id(0xb3f2_56d8_aca0_b0b9), // board:f6:black:bishop
                Id(0x2fd7_e4b9_e72c_d38c), // board:f6:black:rook
                Id(0x61cf_4f94_c97d_f93d), // board:f6:black:queen
                Id(0x4e9d_2827_355f_c492), // board:f6:black:king
            ]),
            RoleTable::new([
                Id(0xdfd3_9533_9cdb_f4a7), // board:f6:white:pawn
                Id(0x0cd9_a497_658a_5698), // board:f6:white:knight
                Id(0x0981_dcd2_96a8_736d), // board:f6:white:bishop
                Id(0x116d_0016_cb94_8f09), // board:f6:white:rook
                Id(0x3a68_53c7_e707_57a7), // board:f6:white:queen
                Id(0x7ca9_723f_bb2e_8988), // board:f6:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x5c82_c505_db9a_b0fa), // board:g6:black:pawn
                Id(0x763c_4a13_71b3_68fd), // board:g6:black:knight
                Id(0xb030_31a8_b451_6e84), // board:g6:black:bishop
                Id(0x65ca_5b96_b755_2210), // board:g6:black:rook
                Id(0x1b6b_aca2_ae4e_125b), // board:g6:black:queen
                Id(0x19eb_b029_435d_cb0f), // board:g6:black:king
            ]),
            RoleTable::new([
                Id(0xef92_7dbc_f00c_20f2), // board:g6:white:pawn
                Id(0x56fd_23c8_f971_5a4c), // board:g6:white:knight
                Id(0x9f65_789a_6509_a440), // board:g6:white:bishop
                Id(0x2cf9_c8ca_052f_6e9f), // board:g6:white:rook
                Id(0x3186_5ced_6120_f37d), // board:g6:white:queen
                Id(0x2785_3383_47f2_ba08), // board:g6:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xfcf7_fe8a_3430_b241), // board:h6:black:pawn
                Id(0xf793_c467_02e0_86a0), // board:h6:black:knight
                Id(0x35dd_37d5_8714_48af), // board:h6:black:bishop
                Id(0xdd69_a0d8_ab3b_546d), // board:h6:black:rook
                Id(0x758f_450c_8857_2e0b), // board:h6:black:queen
                Id(0x4659_d2b7_4384_8a2c), // board:h6:black:king
            ]),
            RoleTable::new([
                Id(0x7b32_f7d1_e036_80ec), // board:h6:white:pawn
                Id(0x284c_847b_9d88_7aae), // board:h6:white:knight
                Id(0x9ff3_8fed_72e9_052f), // board:h6:white:bishop
                Id(0x0b09_0a75_60a9_68e3), // board:h6:white:rook
                Id(0x67fe_f95d_9260_7890), // board:h6:white:queen
                Id(0xc61b_b3a1_41e5_0e8c), // board:h6:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x3253_a729_b9ba_3dde), // board:a7:black:pawn
                Id(0xd728_8e01_2aeb_8d31), // board:a7:black:knight
                Id(0xe9f6_082b_0554_2e4e), // board:a7:black:bishop
                Id(0x604d_51b2_5fbf_70e2), // board:a7:black:rook
                Id(0x959f_587d_507a_8359), // board:a7:black:queen
                Id(0x963e_f2c9_6b33_be31), // board:a7:black:king
            ]),
            RoleTable::new([
                Id(0xb9fd_7620_e731_6243), // board:a7:white:pawn
                Id(0x04fe_abfb_bdb6_19cb), // board:a7:white:knight
                Id(0xe479_ee5b_9930_578c), // board:a7:white:bishop
                Id(0xabee_ddb2_dde0_6ff1), // board:a7:white:rook
                Id(0x1f2b_1d1f_15f6_dc9c), // board:a7:white:queen
                Id(0x150f_361d_ab9d_ec26), // board:a7:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x8c74_c368_081b_3075), // board:b7:black:pawn
                Id(0xde33_6a2a_4bc1_c44b), // board:b7:black:knight
                Id(0xebfa_fa33_d725_4b59), // board:b7:black:bishop
                Id(0x73aa_8a56_4fb7_ac9e), // board:b7:black:rook
                Id(0xb063_e962_e045_f54d), // board:b7:black:queen
                Id(0x74f8_5198_b05a_2e7d), // board:b7:black:king
            ]),
            RoleTable::new([
                Id(0x05a7_e8a5_7db9_1b77), // board:b7:white:pawn
                Id(0x742e_1e65_1c60_ba83), // board:b7:white:knight
                Id(0xe7f2_8ecd_2d49_eecd), // board:b7:white:bishop
                Id(0x58ef_c10b_06a2_068d), // board:b7:white:rook
                Id(0xb69e_38a8_965c_6b65), // board:b7:white:queen
                Id(0x9f6a_419d_3825_95f4), // board:b7:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xb9bc_6c87_167c_33e7), // board:c7:black:pawn
                Id(0x0bf6_92b3_8d07_9f23), // board:c7:black:knight
                Id(0x9255_abb5_0d53_2280), // board:c7:black:bishop
                Id(0x1a8c_1e99_2b94_1148), // board:c7:black:rook
                Id(0x60e8_ed72_c0df_f5d1), // board:c7:black:queen
                Id(0x5a0f_544d_d2b1_fb18), // board:c7:black:king
            ]),
            RoleTable::new([
                Id(0xb588_9c6e_1563_0a75), // board:c7:white:pawn
                Id(0x9a96_32e6_5904_ad3c), // board:c7:white:knight
                Id(0x56c0_74a5_81ea_17fe), // board:c7:white:bishop
                Id(0xc6e5_7a78_fbd9_86e0), // board:c7:white:rook
                Id(0xaa91_19ff_184c_ccf4), // board:c7:white:queen
                Id(0x64a5_3dc9_24fe_7ac9), // board:c7:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x7ef4_8f2b_8302_4e20), // board:d7:black:pawn
                Id(0x2c60_4a7a_1773_26b3), // board:d7:black:knight
                Id(0xb9ab_4ce5_7f2d_34f3), // board:d7:black:bishop
                Id(0xaac4_0a27_03d9_bea0), // board:d7:black:rook
                Id(0x7b64_9785_5532_6f9f), // board:d7:black:queen
                Id(0x0372_7073_c2e1_34b1), // board:d7:black:king
            ]),
            RoleTable::new([
                Id(0x4a75_0a09_ce95_73f7), // board:d7:white:pawn
                Id(0x881b_82a1_3b51_b9e2), // board:d7:white:knight
                Id(0x5544_f7d7_74b1_4aef), // board:d7:white:bishop
                Id(0x2eab_8ca6_3ce8_02d7), // board:d7:white:rook
                Id(0xf43c_7328_73f2_4c13), // board:d7:white:queen
                Id(0x142d_e49f_ff7a_7c3d), // board:d7:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x11d5_05d4_c351_bd7f), // board:e7:black:pawn
                Id(0x4850_e73e_03eb_6064), // board:e7:black:knight
                Id(0x6935_01d6_2829_7551), // board:e7:black:bishop
                Id(0x764d_beae_7fa4_f3a6), // board:e7:black:rook
                Id(0xfd08_0d23_6da8_14ba), // board:e7:black:queen
                Id(0xc7f6_aa2d_e59a_ea61), // board:e7:black:king
            ]),
            RoleTable::new([
                Id(0xcf46_4cec_899a_2f8a), // board:e7:white:pawn
                Id(0x506e_6744_cd97_4924), // board:e7:white:knight
                Id(0x7b3f_0195_fc6f_290f), // board:e7:white:bishop
                Id(0x14a1_9564_0116_f336), // board:e7:white:rook
                Id(0xfb4a_3d79_4a9a_80d2), // board:e7:white:queen
                Id(0x0c33_5248_857f_a9e7), // board:e7:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x6568_fca9_2c76_a243), // board:f7:black:pawn
                Id(0xcfc4_47f1_e53c_8e1b), // board:f7:black:knight
                Id(0xc62c_58f9_7dd9_49bf), // board:f7:black:bishop
                Id(0x1e99_b96e_70a9_be8b), // board:f7:black:rook
                Id(0x8c90_fd9b_083f_4558), // board:f7:black:queen
                Id(0x3527_87ba_a0d7_c22f), // board:f7:black:king
            ]),
            RoleTable::new([
                Id(0xf538_639c_e705_b824), // board:f7:white:pawn
                Id(0xb018_3db5_6ffc_6a79), // board:f7:white:knight
                Id(0x1215_3635_b2c0_cf57), // board:f7:white:bishop
                Id(0x7c08_28dd_624e_c390), // board:f7:white:rook
                Id(0x3550_c232_1fd6_109c), // board:f7:white:queen
                Id(0x0a9c_32d5_eae4_5305), // board:f7:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x4de0_b0f4_0f32_a7b8), // board:g7:black:pawn
                Id(0xb05c_a3f5_6426_8d99), // board:g7:black:knight
                Id(0xcd45_4f8f_19c5_126a), // board:g7:black:bishop
                Id(0x2c5e_9deb_57ef_4743), // board:g7:black:rook
                Id(0x106f_72fe_81e2_c590), // board:g7:black:queen
                Id(0x9853_eab6_3b5e_0b35), // board:g7:black:king
            ]),
            RoleTable::new([
                Id(0x3c79_a0ff_5580_ef7f), // board:g7:white:pawn
                Id(0x0ed9_b915_c66e_d37e), // board:g7:white:knight
                Id(0x7f51_26db_ba5e_0ca7), // board:g7:white:bishop
                Id(0xd74b_be77_e611_6ac7), // board:g7:white:rook
                Id(0x371f_77e7_6bb8_417e), // board:g7:white:queen
                Id(0xe6c4_2178_c4bb_b92e), // board:g7:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x96d6_9346_0cc3_7e5d), // board:h7:black:pawn
                Id(0x9ae1_82c8_bc94_74e8), // board:h7:black:knight
                Id(0xbbe8_3f4e_cc2b_decb), // board:h7:black:bishop
                Id(0x3a93_8fee_32d2_9981), // board:h7:black:rook
                Id(0x7976_033a_39f7_d952), // board:h7:black:queen
                Id(0xabbd_cdd7_ed5c_0860), // board:h7:black:king
            ]),
            RoleTable::new([
                Id(0xede6_c87f_8477_609d), // board:h7:white:pawn
                Id(0x5e11_e86d_5873_d484), // board:h7:white:knight
                Id(0x7a76_956c_3eaf_b413), // board:h7:white:bishop
                Id(0x8044_56af_10f5_fb53), // board:h7:white:rook
                Id(0x6bfa_9aae_5ec0_5779), // board:h7:white:queen
                Id(0x71f1_ce24_90d2_0b07), // board:h7:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x42e2_40cb_6368_9f2f), // board:a8:black:pawn
                Id(0xa4fc_4bd4_fc55_58ca), // board:a8:black:knight
                Id(0xdc84_2b7e_2819_e230), // board:a8:black:bishop
                Id(0x26e6_db8f_fdf5_adfe), // board:a8:black:rook
                Id(0xa4ec_0132_764c_a04b), // board:a8:black:queen
                Id(0xcf05_daf5_ac8d_77b0), // board:a8:black:king
            ]),
            RoleTable::new([
                Id(0x799e_81f0_5bc9_3f31), // board:a8:white:pawn
                Id(0xf678_647e_3519_ac6e), // board:a8:white:knight
                Id(0x3d57_74a1_1d31_ab39), // board:a8:white:bishop
                Id(0xebe9_ea2a_df43_21c7), // board:a8:white:rook
                Id(0xcd04_f3ff_001a_4778), // board:a8:white:queen
                Id(0xf1bc_c3d2_75af_e51a), // board:a8:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x6d2b_dcda_e291_9661), // board:b8:black:pawn
                Id(0xe755_178d_58fc_4e76), // board:b8:black:knight
                Id(0xba89_142e_0075_03b8), // board:b8:black:bishop
                Id(0x4693_56c5_04ec_9f9d), // board:b8:black:rook
                Id(0x733e_a705_fae4_fa77), // board:b8:black:queen
                Id(0x49ca_d48c_ebf4_a71e), // board:b8:black:king
            ]),
            RoleTable::new([
                Id(0x8653_6b8c_f342_8a8c), // board:b8:white:pawn
                Id(0x1b85_d488_d0f2_0cc5), // board:b8:white:knight
                Id(0x8a1b_0838_21f4_0cb4), // board:b8:white:bishop
                Id(0x0321_9a39_ee58_7a30), // board:b8:white:rook
                Id(0xe327_3522_0644_80ca), // board:b8:white:queen
                Id(0xe728_e8c8_3c33_4074), // board:b8:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x4288_0b02_36e4_d951), // board:c8:black:pawn
                Id(0x69b9_7db1_a4c0_3dfe), // board:c8:black:knight
                Id(0xa3bc_941d_0a50_61cb), // board:c8:black:bishop
                Id(0xc876_3c5b_08d1_908c), // board:c8:black:rook
                Id(0xb4d8_f77b_c3e5_6167), // board:c8:black:queen
                Id(0x7a4c_10ec_2158_c4a6), // board:c8:black:king
            ]),
            RoleTable::new([
                Id(0x97d7_374c_6008_7b73), // board:c8:white:pawn
                Id(0xdab9_fe65_25d8_9021), // board:c8:white:knight
                Id(0x7b4a_38e3_2537_df62), // board:c8:white:bishop
                Id(0x4978_7fef_17af_9924), // board:c8:white:rook
                Id(0x9f91_508b_ffcf_c14a), // board:c8:white:queen
                Id(0x96fb_f83a_1288_4624), // board:c8:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x5f0f_4a58_9817_1bb6), // board:d8:black:pawn
                Id(0xf9b5_b7c4_acc6_7c96), // board:d8:black:knight
                Id(0xe9f6_760e_32cd_8021), // board:d8:black:bishop
                Id(0x3f6c_6af8_59d8_0055), // board:d8:black:rook
                Id(0x9e21_f4f9_03b3_3fd9), // board:d8:black:queen
                Id(0xd9e9_2aa2_46bf_719e), // board:d8:black:king
            ]),
            RoleTable::new([
                Id(0xa246_637c_ff32_8532), // board:d8:white:pawn
                Id(0x0d15_1d86_adb7_3615), // board:d8:white:knight
                Id(0x9501_1364_6d1d_6e03), // board:d8:white:bishop
                Id(0xa1e9_300c_d852_0548), // board:d8:white:rook
                Id(0x049a_7f41_061a_9e60), // board:d8:white:queen
                Id(0x81a1_549f_d657_3da5), // board:d8:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x39f8_90f5_79f9_2f88), // board:e8:black:pawn
                Id(0xfc6a_82d6_4b86_55fb), // board:e8:black:knight
                Id(0x09c7_e552_bc76_492f), // board:e8:black:bishop
                Id(0x7f7c_c394_20a3_a545), // board:e8:black:rook
                Id(0x9d76_5e41_9fb6_9f6d), // board:e8:black:queen
                Id(0x13ae_978d_09fe_5557), // board:e8:black:king
            ]),
            RoleTable::new([
                Id(0x043f_cae6_0cc0_eba0), // board:e8:white:pawn
                Id(0xa865_a54e_dcc0_f019), // board:e8:white:knight
                Id(0x4da8_979a_0041_e8a9), // board:e8:white:bishop
                Id(0x5b45_e522_e4b1_b4ef), // board:e8:white:rook
                Id(0xfcb6_be43_a9f2_fe9b), // board:e8:white:queen
                Id(0x5fa7_867c_af35_e149), // board:e8:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x93c5_b5f4_7356_388b), // board:f8:black:pawn
                Id(0x9c68_4cb6_c4d2_4417), // board:f8:black:knight
                Id(0x852f_5493_4da5_5cc9), // board:f8:black:bishop
                Id(0x9bfb_227e_bdf4_c5ce), // board:f8:black:rook
                Id(0xd30c_088b_a61e_a5ef), // board:f8:black:queen
                Id(0x7304_99af_9215_49ff), // board:f8:black:king
            ]),
            RoleTable::new([
                Id(0x920e_4495_35dd_359e), // board:f8:white:pawn
                Id(0x93c4_2566_aef9_8ffb), // board:f8:white:knight
                Id(0x3bc3_6e07_8f75_15d7), // board:f8:white:bishop
                Id(0xb49c_3b39_9509_1a36), // board:f8:white:rook
                Id(0x08de_8a1c_7797_da9b), // board:f8:white:queen
                Id(0x5698_6e2e_f3ed_091b), // board:f8:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x63dc_359d_8d23_1b78), // board:g8:black:pawn
                Id(0x8ec9_7d29_1745_6ed0), // board:g8:black:knight
                Id(0x8107_fccf_064f_cf56), // board:g8:black:bishop
                Id(0x8903_9d79_d6fc_5c5c), // board:g8:black:rook
                Id(0x5d94_337f_bfaf_7f5b), // board:g8:black:queen
                Id(0x4e4b_705b_9290_3ba4), // board:g8:black:king
            ]),
            RoleTable::new([
                Id(0x70eb_093b_15b2_90cc), // board:g8:white:pawn
                Id(0x99e7_afea_be00_0731), // board:g8:white:knight
                Id(0x5d0a_12f2_7ad3_10d1), // board:g8:white:bishop
                Id(0xd449_0ad5_26f1_4431), // board:g8:white:rook
                Id(0x8f98_87e6_0787_35a1), // board:g8:white:queen
                Id(0x917f_1dd5_f888_6c61), // board:g8:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xec16_ca8a_ea98_ad76), // board:h8:black:pawn
                Id(0x6703_df9d_2924_e97e), // board:h8:black:knight
                Id(0x0989_54d5_1fff_6580), // board:h8:black:bishop
                Id(0x8fe8_8b57_305e_2ab6), // board:h8:black:rook
                Id(0x1a4e_4822_eb4d_7a59), // board:h8:black:queen
                Id(0xff57_7222_c14f_0a3a), // board:h8:black:king
            ]),
            RoleTable::new([
                Id(0x73a1_9219_1659_1cbd), // board:h8:white:pawn
                Id(0x48cb_ff08_6ddf_285a), // board:h8:white:knight
                Id(0x7f9d_1a2e_1ebe_1327), // board:h8:white:bishop
                Id(0x12a8_f216_af94_18c2), // board:h8:white:rook
                Id(0xb5b4_071d_bfc7_3a66), // board:h8:white:queen
                Id(0xd20d_8c88_c8ff_e65f), // board:h8:white:king
            ]),
        ]),
    ]),
    turn: PlayerTable::new([
        Id(0x0000_0000_0000_0000), // turn:black
        Id(0xf8d6_26aa_af27_8509), // turn:white
    ]),
    castle: PlayerTable::new([
        FileTable::new([
            Id(0x1ef6_e6db_b196_1ec9), // castle:black:a
            Id(0x0000_0000_0000_0000), // castle:black:b
            Id(0x0000_0000_0000_0000), // castle:black:c
            Id(0x0000_0000_0000_0000), // castle:black:d
            Id(0x0000_0000_0000_0000), // castle:black:e
            Id(0x0000_0000_0000_0000), // castle:black:f
            Id(0x0000_0000_0000_0000), // castle:black:g
            Id(0xa57e_6339_dd2c_f3a0), // castle:black:h
        ]),
        FileTable::new([
            Id(0xf165_b587_df89_8190), // castle:white:a
            Id(0x0000_0000_0000_0000), // castle:white:b
            Id(0x0000_0000_0000_0000), // castle:white:c
            Id(0x0000_0000_0000_0000), // castle:white:d
            Id(0x0000_0000_0000_0000), // castle:white:e
            Id(0x0000_0000_0000_0000), // castle:white:f
            Id(0x0000_0000_0000_0000), // castle:white:g
            Id(0x31d7_1dce_64b2_c310), // castle:white:h
        ]),
    ]),
    en_passant: EnPassantTable::new([
        Id(0x70cc_73d9_0bc2_6e24), // en-passant:a3
        Id(0xe21a_6b35_df0c_3ad7), // en-passant:b3
        Id(0x003a_93d8_b280_6962), // en-passant:c3
        Id(0x1c99_ded3_3cb8_90a1), // en-passant:d3
        Id(0xcf31_45de_0add_4289), // en-passant:e3
        Id(0xd0e4_427a_5514_fb72), // en-passant:f3
        Id(0x77c6_21cc_9fb3_a483), // en-passant:g3
        Id(0x67a3_4dac_4356_550b), // en-passant:h3
        Id(0x70cc_73d9_0bc2_6e24), // en-passant:a6
        Id(0xe21a_6b35_df0c_3ad7), // en-passant:b6
        Id(0x003a_93d8_b280_6962), // en-passant:c6
        Id(0x1c99_ded3_3cb8_90a1), // en-passant:d6
        Id(0xcf31_45de_0add_4289), // en-passant:e6
        Id(0xd0e4_427a_5514_fb72), // en-passant:f6
        Id(0x77c6_21cc_9fb3_a483), // en-passant:g6
        Id(0x67a3_4dac_4356_550b), // en-passant:h6
    ]),
};
