// Generated by scripts/standard-id.rs.
pub const STANDARD: Basis = Basis {
    board: SquareTable::new([
        PlayerTable::new([
            RoleTable::new([
                Id(0x924a_ba91_a57a_42ae_04af_0844_3527_9166), // board:a1:black:pawn
                Id(0x69c8_16fe_31d0_5518_1d74_cb1d_1611_6d16), // board:a1:black:knight
                Id(0xe468_6a8f_ab0f_d717_c0d1_7795_a5d8_5dfd), // board:a1:black:bishop
                Id(0x9ed6_3a41_39b5_946a_1f2b_fd51_0c78_ce3d), // board:a1:black:rook
                Id(0xc741_a187_8d71_df77_324b_d4c1_8495_1f69), // board:a1:black:queen
                Id(0xacfa_458a_a605_9897_63b3_cc17_a212_1c2b), // board:a1:black:king
            ]),
            RoleTable::new([
                Id(0xd67b_e1a0_2c41_25a4_a510_3673_dd0a_fe51), // board:a1:white:pawn
                Id(0x6a4a_be10_d3f7_23c0_b139_d905_70e2_5b74), // board:a1:white:knight
                Id(0x7e3c_b6db_20c6_4a58_8504_c39b_1db6_b43b), // board:a1:white:bishop
                Id(0xdc18_84f7_f184_fb1f_7069_d5cc_a50e_bbd2), // board:a1:white:rook
                Id(0x5e60_eee6_a953_a044_eb12_2f24_5095_ddca), // board:a1:white:queen
                Id(0xb95f_0976_df16_19a6_439e_8537_8e5b_04cd), // board:a1:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xc0c8_577c_4b85_ad06_d536_ebe7_aaaa_ca8e), // board:b1:black:pawn
                Id(0x487f_af12_c0ce_c6a3_6c22_4dc3_bba6_9bd9), // board:b1:black:knight
                Id(0x22dc_854e_07ad_a97d_f118_01e2_66b7_486c), // board:b1:black:bishop
                Id(0xed4b_7eaa_e1e6_41cf_c8d7_cb2e_2769_3fed), // board:b1:black:rook
                Id(0x43b1_db37_80c1_26e0_8797_c963_a577_cda0), // board:b1:black:queen
                Id(0x3482_cbdd_d825_19cb_39a8_6665_5164_4fc9), // board:b1:black:king
            ]),
            RoleTable::new([
                Id(0x375c_41f8_9ef3_9d99_b5ec_bd65_1960_7e02), // board:b1:white:pawn
                Id(0x28bd_186c_dbb6_612d_5c92_0806_209d_f00f), // board:b1:white:knight
                Id(0xdff1_9692_1fa5_09aa_5d59_246b_f591_827f), // board:b1:white:bishop
                Id(0xab38_1993_1225_5b77_b15e_8650_de6d_2143), // board:b1:white:rook
                Id(0x6289_88b6_c58d_0f8c_2283_d1b7_f42f_c8cf), // board:b1:white:queen
                Id(0xf4eb_29e8_fa14_b546_0bf1_5e1d_3bf5_0c9e), // board:b1:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x5dee_d460_8447_9d55_aaba_2a7a_e9c2_b777), // board:c1:black:pawn
                Id(0xb24c_3347_2c11_e346_5ffa_7444_a253_7615), // board:c1:black:knight
                Id(0xa8bb_3d25_7f5a_c1c9_ea32_b7d4_2620_04f9), // board:c1:black:bishop
                Id(0x8638_0906_8ea7_df19_0386_8f29_4adb_4915), // board:c1:black:rook
                Id(0xf4d7_4aa7_d884_08a8_5016_96ee_2e80_9063), // board:c1:black:queen
                Id(0x033a_14d4_0b77_f9ec_bc4b_ba94_44ed_4773), // board:c1:black:king
            ]),
            RoleTable::new([
                Id(0x124d_4087_72ba_0184_6543_e31d_8af3_99cf), // board:c1:white:pawn
                Id(0xf71b_e504_d5dc_c5e3_073e_fa41_c866_5456), // board:c1:white:knight
                Id(0x2a41_049e_ea54_0113_1ddd_371c_320a_a5f6), // board:c1:white:bishop
                Id(0x2665_d10b_9317_1671_d391_10f6_c6f1_f266), // board:c1:white:rook
                Id(0x22a8_7482_43f8_79cb_9420_f499_319a_e63d), // board:c1:white:queen
                Id(0x2275_6017_dfc4_b682_16d4_3df9_11e7_4bce), // board:c1:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x29ff_c296_f2a7_9761_8930_ae19_8a18_8041), // board:d1:black:pawn
                Id(0x558b_4c71_6949_0745_0732_5cf9_28b8_5fe2), // board:d1:black:knight
                Id(0x04d8_0ea7_da69_9053_d23e_9840_a04c_072d), // board:d1:black:bishop
                Id(0xf5f5_5e28_0b57_d3ce_0b06_391a_fbf8_2977), // board:d1:black:rook
                Id(0x9c2d_3213_857a_e8c1_4891_84af_4504_1ea2), // board:d1:black:queen
                Id(0xf020_8567_d8c8_3eb8_74de_4e06_afcf_c7f4), // board:d1:black:king
            ]),
            RoleTable::new([
                Id(0xb3c2_d190_1072_2bff_033b_957d_e517_54da), // board:d1:white:pawn
                Id(0x4714_878b_0d27_d34b_63f2_eb89_e8ae_e23f), // board:d1:white:knight
                Id(0x60ab_d644_7d64_0bfa_2992_166b_68a3_4142), // board:d1:white:bishop
                Id(0x97da_86c1_60b9_e7c7_7f81_9506_1184_612b), // board:d1:white:rook
                Id(0xd7ce_df08_6be8_1e6b_de16_0daa_a02f_b7a0), // board:d1:white:queen
                Id(0xeead_3f45_aa9c_76c0_bad4_a52d_8e5d_c1db), // board:d1:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x003a_78e3_c18c_731b_b1e2_7545_74e6_ba37), // board:e1:black:pawn
                Id(0x40b1_ed5e_bbe1_e1ed_66e1_0b57_521e_da4f), // board:e1:black:knight
                Id(0x85cb_39c7_0ca2_b7cf_f6f0_95ea_9557_0384), // board:e1:black:bishop
                Id(0x8167_e07e_e691_ca05_ca26_30a6_58a0_ec20), // board:e1:black:rook
                Id(0x5ffa_b2ec_d54e_32d5_cc60_f2d8_6190_d592), // board:e1:black:queen
                Id(0x3cc0_f5d3_9d4c_45a2_16f3_5b47_f6b6_987f), // board:e1:black:king
            ]),
            RoleTable::new([
                Id(0x96e9_ae45_6511_f3bd_654e_5c39_8456_1e5a), // board:e1:white:pawn
                Id(0x47e0_5916_34af_bdda_23c9_7b0d_2100_8b7f), // board:e1:white:knight
                Id(0x804d_036b_6876_57ac_f44c_f271_e739_a9ed), // board:e1:white:bishop
                Id(0xd623_8630_c298_d18b_adfe_7723_2d28_9caa), // board:e1:white:rook
                Id(0xa596_9f2f_38c3_8cc7_7379_eef6_1c11_79ac), // board:e1:white:queen
                Id(0x926e_66e2_3bcb_4fb4_b3dd_708c_773c_51dd), // board:e1:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x131f_441a_af4a_1d6d_014b_f759_91eb_0e01), // board:f1:black:pawn
                Id(0xd994_8b47_7a1c_8773_df26_0c91_2c80_81a4), // board:f1:black:knight
                Id(0x5236_bb45_e2fe_09a7_e93c_7fdc_193b_4788), // board:f1:black:bishop
                Id(0x5ea1_5335_2e45_4086_77d7_f045_0912_b9d6), // board:f1:black:rook
                Id(0x234e_4771_efc2_c75b_128e_6038_2242_b1e6), // board:f1:black:queen
                Id(0xb454_7417_ea73_89f8_f752_5368_8015_6ecd), // board:f1:black:king
            ]),
            RoleTable::new([
                Id(0x8ca1_3ca4_67c6_ebd7_51c4_365c_ab32_0be7), // board:f1:white:pawn
                Id(0x7bee_2a2e_6252_1457_65b1_8632_e99a_79a3), // board:f1:white:knight
                Id(0xf12d_a721_9c3b_3984_fca8_f60b_5c3a_4745), // board:f1:white:bishop
                Id(0x01fc_8f31_6cf0_3ab3_a990_73c1_c880_7148), // board:f1:white:rook
                Id(0xa174_2e22_6f9c_a729_3c97_8b26_7fde_3b6f), // board:f1:white:queen
                Id(0x0722_c85a_04df_994a_d5cf_cb4a_ca43_01d2), // board:f1:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xcf73_dba4_abdc_05dc_37b3_6dc9_6df8_d475), // board:g1:black:pawn
                Id(0x5adb_86c4_865e_3971_392d_396b_eeb0_1fe9), // board:g1:black:knight
                Id(0x471b_3309_23f4_9be1_8ca2_3678_2b37_b1e5), // board:g1:black:bishop
                Id(0x658c_51bf_55f0_477e_82b5_eb0e_20b2_a975), // board:g1:black:rook
                Id(0x56b1_ae02_0a5c_c7fc_2e8a_8a27_c33a_1a0c), // board:g1:black:queen
                Id(0x6623_57fa_1430_ccfc_2d6d_5803_7261_ee3e), // board:g1:black:king
            ]),
            RoleTable::new([
                Id(0xc0c9_290b_9502_7725_dabf_899c_e4c6_fab0), // board:g1:white:pawn
                Id(0xe623_96bf_db08_0734_323d_8445_76da_ee7e), // board:g1:white:knight
                Id(0xc261_3bfd_e88c_a2e6_cb76_62e2_370e_02ea), // board:g1:white:bishop
                Id(0x023c_dc44_7de9_9a87_adda_8e02_2c42_9f74), // board:g1:white:rook
                Id(0x65c8_2e20_0f11_50bc_dc2b_43dc_b9d4_76d3), // board:g1:white:queen
                Id(0x898a_0f11_c9e9_249d_5b05_df87_924e_ea52), // board:g1:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x3d19_006c_c217_4d5c_2acf_ec8c_c87b_5845), // board:h1:black:pawn
                Id(0xf4aa_a0a8_3601_71c7_7c44_a4b7_bbde_c9c8), // board:h1:black:knight
                Id(0xb4e2_cd05_5817_9fb8_2e69_822d_ffb3_d9d1), // board:h1:black:bishop
                Id(0x9b56_ca96_c9c0_2c6b_b7ea_88dd_bd56_f5f8), // board:h1:black:rook
                Id(0x4829_5bc7_62b0_1702_1419_4e6f_5409_2b6e), // board:h1:black:queen
                Id(0xd761_8a85_cf22_f22c_23e1_da9c_bac4_c17e), // board:h1:black:king
            ]),
            RoleTable::new([
                Id(0x0518_fa4c_bc64_fe24_8c1a_d27a_e48f_7abd), // board:h1:white:pawn
                Id(0xf799_6465_dfd3_c3c9_8f95_f5ff_8af2_eaa2), // board:h1:white:knight
                Id(0x8fd4_af60_6f51_6992_10db_e443_7ff1_1790), // board:h1:white:bishop
                Id(0x68fe_b7b9_cdf2_4e8d_f922_054c_a37d_4069), // board:h1:white:rook
                Id(0xac35_ad38_9d31_c157_03e2_d503_471a_9dbe), // board:h1:white:queen
                Id(0x4c77_2b0e_a6af_ab90_3c21_3d2a_9622_f91c), // board:h1:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x2ba7_0d5f_c15a_a035_d3c5_ea72_5325_c0af), // board:a2:black:pawn
                Id(0x3db0_ccd9_cf24_004a_20f4_2054_c957_872b), // board:a2:black:knight
                Id(0xaf02_aadc_91d1_a9a4_d626_550c_961f_56fe), // board:a2:black:bishop
                Id(0x42b5_5b27_1085_48e7_b012_da3e_7934_944f), // board:a2:black:rook
                Id(0x6c6a_0b6f_5b35_bcfb_59df_8593_f483_883e), // board:a2:black:queen
                Id(0x42b7_5506_b09d_d059_1349_3913_ccaf_b249), // board:a2:black:king
            ]),
            RoleTable::new([
                Id(0x9ad0_204b_2bfc_1f4f_b434_88e4_67b5_b93f), // board:a2:white:pawn
                Id(0xbbc0_a8f8_3cb4_bd02_2e62_e2c1_7a9b_1a53), // board:a2:white:knight
                Id(0xf79f_8734_74c5_95cc_e985_618c_6ad8_2efd), // board:a2:white:bishop
                Id(0xb904_3c83_ec21_be9f_301e_a92e_04bb_8c0c), // board:a2:white:rook
                Id(0x9e7a_4951_2053_da3c_25c9_7c1f_2cf1_b01c), // board:a2:white:queen
                Id(0xcfbc_a16d_8e7c_28eb_99e3_a01b_aae2_f5db), // board:a2:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xaea6_c03d_d2e9_c2ee_46f6_cc2c_c40a_e2cc), // board:b2:black:pawn
                Id(0x2606_575c_15f4_88ac_36e5_e343_f87f_11aa), // board:b2:black:knight
                Id(0xfd6b_738d_705c_c9b3_a026_aab9_d63b_3129), // board:b2:black:bishop
                Id(0x0c67_5cbc_70ef_7030_06f3_078d_e348_4172), // board:b2:black:rook
                Id(0xa7bd_10db_2ad3_9983_328f_b2f5_05b8_4430), // board:b2:black:queen
                Id(0x65cc_0a83_5b35_4207_6d08_37b7_889a_fe36), // board:b2:black:king
            ]),
            RoleTable::new([
                Id(0x854f_cb91_27a1_759e_bcc0_35d0_b4da_6434), // board:b2:white:pawn
                Id(0x6f50_5ea0_ed87_1259_30f9_249f_8aea_7117), // board:b2:white:knight
                Id(0xf4c7_fedb_14f8_08ed_1708_a7e7_6cec_4fab), // board:b2:white:bishop
                Id(0xd0d7_618e_70df_8555_d13b_0dbc_5d8b_0d1e), // board:b2:white:rook
                Id(0xc7d5_3c0c_3818_746e_eed8_d25e_1242_074e), // board:b2:white:queen
                Id(0xa307_c85e_4c8b_2c71_c7e7_9be1_2dce_2692), // board:b2:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x0bb2_5568_b979_73c9_162a_c8f9_801f_3a40), // board:c2:black:pawn
                Id(0xe8be_fa99_70c9_1edc_b178_d84f_1c69_8434), // board:c2:black:knight
                Id(0xeb2b_cfb9_610f_07e8_314a_b6fb_0c01_964f), // board:c2:black:bishop
                Id(0x0d03_406c_a38b_2134_6eea_fafd_46b6_9306), // board:c2:black:rook
                Id(0x9390_1710_f338_d030_175a_5cd0_ca23_f48e), // board:c2:black:queen
                Id(0xe468_5f8d_64c6_e5aa_5205_7532_9bd7_85c2), // board:c2:black:king
            ]),
            RoleTable::new([
                Id(0x726c_c6a4_c664_db5a_a46f_6bec_9ebe_cc23), // board:c2:white:pawn
                Id(0x974a_f4cb_1d9c_8ec4_f015_ba76_e05b_353c), // board:c2:white:knight
                Id(0xf1cb_5a9a_737a_bef9_f670_d5e3_877f_382d), // board:c2:white:bishop
                Id(0xf475_500e_43b0_ebf7_ed1e_48fd_3da4_eb4d), // board:c2:white:rook
                Id(0x524b_432e_17b5_7162_b217_c603_a4b1_75c6), // board:c2:white:queen
                Id(0xfe35_1a6d_e1fc_4df3_0276_ea90_4d99_abd2), // board:c2:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x4420_8897_8c06_ec42_59d5_a747_5a7c_2297), // board:d2:black:pawn
                Id(0xe85d_481a_d76d_a9eb_d152_7a03_27d1_e9f4), // board:d2:black:knight
                Id(0x4393_8fa4_a6e6_7fed_cb13_38cf_f81d_62d7), // board:d2:black:bishop
                Id(0x819c_41cb_1f95_2519_109e_243c_e1d6_d364), // board:d2:black:rook
                Id(0x70cc_c5e1_f335_7d6e_6411_d51c_e386_f31c), // board:d2:black:queen
                Id(0x7109_9e62_45ad_2c7e_b14d_051a_e522_dd66), // board:d2:black:king
            ]),
            RoleTable::new([
                Id(0x3b31_c5d8_d858_7d52_0591_dc1e_e482_b402), // board:d2:white:pawn
                Id(0x09ce_ecd9_3d82_0ea4_8a84_0b0b_2acc_3d67), // board:d2:white:knight
                Id(0xcbca_b7e2_260c_f95a_805e_8f85_5ca5_4d65), // board:d2:white:bishop
                Id(0xdcda_1e4e_51a0_7b96_20ac_7f41_530a_43f6), // board:d2:white:rook
                Id(0xbfc9_4cb0_4f0c_772d_e4b1_15a5_255c_e0f5), // board:d2:white:queen
                Id(0x3b71_a831_311f_7041_913e_fd5b_e417_2956), // board:d2:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xef83_13a0_633d_adbe_7018_24d3_3438_ad99), // board:e2:black:pawn
                Id(0x6b15_f729_ab73_d591_8ba2_5dd8_e8bc_ebd9), // board:e2:black:knight
                Id(0x7ad1_f4f0_ebf0_f3f8_2743_466f_1d96_3983), // board:e2:black:bishop
                Id(0x3d9b_dde1_ac9e_4e77_0988_c140_ba72_1ed6), // board:e2:black:rook
                Id(0xe8bd_31f1_9dd6_c9ee_f3e2_4d2a_2c39_7044), // board:e2:black:queen
                Id(0x2fd1_ec29_2e87_e09c_b241_dbfd_4164_38d8), // board:e2:black:king
            ]),
            RoleTable::new([
                Id(0x1091_64f3_4a54_b36c_2537_238b_11ff_259d), // board:e2:white:pawn
                Id(0x451b_3fe9_2281_a3a1_a952_142a_1361_a951), // board:e2:white:knight
                Id(0x571a_574f_451a_5c17_ff34_be58_04a2_d3bd), // board:e2:white:bishop
                Id(0x04e6_0ca7_01a5_da6d_e1f8_2b9d_6a9e_58ff), // board:e2:white:rook
                Id(0x3494_94e0_9f16_36a0_de7f_3210_5b06_e311), // board:e2:white:queen
                Id(0x2911_c513_7973_62ea_f3fc_2f68_1e88_839c), // board:e2:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x615b_7db6_5f77_8265_fd0c_f8fe_84b5_6bb9), // board:f2:black:pawn
                Id(0x8391_b938_0d6a_2b68_6546_f86a_5691_b6f0), // board:f2:black:knight
                Id(0x630c_a612_6860_4da0_1c45_ae36_4d4a_3824), // board:f2:black:bishop
                Id(0x8e28_199c_5baf_ef4e_ae09_ccc3_9eb8_4716), // board:f2:black:rook
                Id(0xb71b_33fe_9fd5_0354_8a01_2150_bcad_1ca0), // board:f2:black:queen
                Id(0xc231_222a_7b90_3e67_574c_ea68_602f_4f63), // board:f2:black:king
            ]),
            RoleTable::new([
                Id(0x4042_cca9_de7b_6b58_1051_8833_1a50_974a), // board:f2:white:pawn
                Id(0x9eec_f4d0_c94a_b922_debf_2c4e_ce99_c428), // board:f2:white:knight
                Id(0x0b22_ede8_d44b_221a_a6a3_414c_96bc_da6d), // board:f2:white:bishop
                Id(0x109a_1517_da08_e1a4_c711_10d2_223e_c65c), // board:f2:white:rook
                Id(0x9838_edfb_77c2_d8aa_bbc6_68cc_0f28_a73d), // board:f2:white:queen
                Id(0xf9eb_5527_fd83_9f14_e86a_413c_cd0d_388d), // board:f2:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x49a6_9ff3_ed09_22ed_2cb1_f99d_cab6_9077), // board:g2:black:pawn
                Id(0xdf2f_b01c_b0fc_d1d7_38e2_7536_6b12_6b30), // board:g2:black:knight
                Id(0xcfce_14f4_404b_1896_f8f0_3c06_5e05_dabc), // board:g2:black:bishop
                Id(0x40c4_666c_d912_eb7f_f7ba_3090_c482_0f59), // board:g2:black:rook
                Id(0xadb7_3898_47bd_a720_01e1_3b1b_3ae1_a34d), // board:g2:black:queen
                Id(0x4847_c804_7268_94e0_44a6_f990_0cf4_335c), // board:g2:black:king
            ]),
            RoleTable::new([
                Id(0xc754_9037_a3d3_b8da_ed22_a0b7_bcce_37ab), // board:g2:white:pawn
                Id(0x63ab_4d6d_d189_203f_3ebd_0638_3ab0_9da3), // board:g2:white:knight
                Id(0x0370_9fc0_4d4b_8860_a244_f34f_5728_9822), // board:g2:white:bishop
                Id(0xe1fc_88b7_034b_8664_63e0_b324_365c_40d1), // board:g2:white:rook
                Id(0xa3ca_8bdd_973d_7269_2c02_b012_a939_fc30), // board:g2:white:queen
                Id(0x2a41_3e7f_5a1f_994d_283b_3db2_f40c_e92b), // board:g2:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xfaab_eee8_aaea_2c66_ff08_aa2b_230d_997b), // board:h2:black:pawn
                Id(0xb6a4_4986_fc65_9de8_366a_0b02_aa27_807b), // board:h2:black:knight
                Id(0x77c8_881f_0568_b364_6aaa_7a59_9ecf_9e25), // board:h2:black:bishop
                Id(0xef24_b970_078d_7805_a1a4_6660_ec62_04c5), // board:h2:black:rook
                Id(0x5db7_6550_4f38_dde6_6d2b_342b_7db6_dceb), // board:h2:black:queen
                Id(0x054a_1f84_323a_ac59_95bd_5b22_8cf0_f762), // board:h2:black:king
            ]),
            RoleTable::new([
                Id(0xf24b_d660_94aa_c9f0_7b17_59d3_0c71_52c6), // board:h2:white:pawn
                Id(0xa726_ffdc_4f79_fd2b_949a_a0e7_46b2_11c7), // board:h2:white:knight
                Id(0x5401_e8b9_a128_dfb5_12b9_a782_e424_4025), // board:h2:white:bishop
                Id(0x2aa9_be66_15d4_8165_8cd5_12dc_a085_dee9), // board:h2:white:rook
                Id(0xb80e_e579_5473_d6e3_4c71_8a75_f12a_aa17), // board:h2:white:queen
                Id(0x3599_9850_9fa3_7d53_15b9_84d8_3ad5_9507), // board:h2:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x2ed8_d1e1_77d2_d049_f3e3_a65b_87f7_b5ca), // board:a3:black:pawn
                Id(0xc0a7_0e92_953b_dfcb_dd0b_de06_b22c_f345), // board:a3:black:knight
                Id(0xb068_8db7_1b83_a1e5_47a1_818b_6aee_23cb), // board:a3:black:bishop
                Id(0xb455_0782_33e6_1988_70b9_bcdc_0740_6164), // board:a3:black:rook
                Id(0x9e00_2a1f_16d3_be88_6e0f_c1f1_5d6f_c969), // board:a3:black:queen
                Id(0xc863_8d19_2b74_96d4_5d56_f262_349a_f145), // board:a3:black:king
            ]),
            RoleTable::new([
                Id(0x9272_c29c_bd0e_118d_716f_deaf_506e_972e), // board:a3:white:pawn
                Id(0x1eb5_bc47_3859_1da3_08d3_5e08_affe_e2ba), // board:a3:white:knight
                Id(0xfd52_2345_89eb_8e64_b578_1d46_6285_cc30), // board:a3:white:bishop
                Id(0xb8ba_7d1d_84ff_5071_22b8_df2d_5079_5512), // board:a3:white:rook
                Id(0x26a9_125c_6542_0089_d3e6_0674_6f09_d25f), // board:a3:white:queen
                Id(0xf6a3_0657_5a02_d4b0_2368_49f1_0dc8_bcb6), // board:a3:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xfd9f_2ca9_118c_317b_10cb_602e_3b78_e626), // board:b3:black:pawn
                Id(0x958e_e781_0575_57da_1f38_880c_23c8_93e3), // board:b3:black:knight
                Id(0x0370_97ce_6e28_3669_3fe9_d52a_b7e8_4a7f), // board:b3:black:bishop
                Id(0x9408_7388_3ae6_34bb_3d4a_e838_2447_4d75), // board:b3:black:rook
                Id(0x585a_231f_3c3f_4375_1d86_3251_b04d_dbb3), // board:b3:black:queen
                Id(0xfd51_fe94_016d_9d96_7109_3ba8_86e8_e6f4), // board:b3:black:king
            ]),
            RoleTable::new([
                Id(0xf4b4_ae24_65a7_3e1d_245e_1e4e_0e9d_b2aa), // board:b3:white:pawn
                Id(0x3d2d_cc16_1e26_6780_52f9_7c16_c4ce_57d3), // board:b3:white:knight
                Id(0xfcee_cb1a_c6de_d28e_4e23_c5c5_653f_d92e), // board:b3:white:bishop
                Id(0x47b6_ec7a_3f0c_de30_01bc_54f9_b6d8_e986), // board:b3:white:rook
                Id(0xa9ae_5b91_bd37_1b18_2d90_5a1c_78cd_e86d), // board:b3:white:queen
                Id(0xed17_ffba_fcc0_ff20_faeb_aa67_ea96_b300), // board:b3:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x916c_d33e_fb7d_4d10_710b_dfcf_ca2a_481b), // board:c3:black:pawn
                Id(0x217c_1818_2222_156e_7e89_e8f9_0f4e_f78e), // board:c3:black:knight
                Id(0x4013_2335_eaa7_9e51_b17b_f890_1681_af22), // board:c3:black:bishop
                Id(0xf069_dc4c_5837_0d6a_d63a_9ba9_cb13_2fbb), // board:c3:black:rook
                Id(0xf51f_0b3e_3690_acd6_bab4_bab4_bbb4_c68c), // board:c3:black:queen
                Id(0x9a87_88b4_f99d_474f_b430_e70f_36d6_7ad2), // board:c3:black:king
            ]),
            RoleTable::new([
                Id(0xc533_a149_ddb3_0eb9_8386_2407_95dc_9745), // board:c3:white:pawn
                Id(0x882a_129a_8580_1427_b5d1_8d86_242e_6ec2), // board:c3:white:knight
                Id(0xb7c3_01e6_c991_d756_d9d8_3cce_f38e_500c), // board:c3:white:bishop
                Id(0x93c4_683c_cfbd_e6b5_87eb_6b68_42b4_5b69), // board:c3:white:rook
                Id(0x6f9b_847e_b8b5_33a9_78bc_a6fd_a835_d351), // board:c3:white:queen
                Id(0x7448_6a00_1860_472f_e35c_7043_0a8b_c2a1), // board:c3:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xcc5a_6a73_e686_1498_28f9_41ba_601b_0ab6), // board:d3:black:pawn
                Id(0x0e3a_cc3e_eaec_ad36_1259_e656_dd29_a51f), // board:d3:black:knight
                Id(0x5300_947e_2964_61ee_338a_fdf9_c597_8d10), // board:d3:black:bishop
                Id(0x1515_c1e6_7bcd_d5d1_994f_a993_fca7_36ac), // board:d3:black:rook
                Id(0x5523_c3af_bf43_7298_7bbb_0fb9_5445_4d12), // board:d3:black:queen
                Id(0xffef_e13a_a06e_8b89_a9da_e588_552b_9485), // board:d3:black:king
            ]),
            RoleTable::new([
                Id(0xda41_2ca0_dc86_0438_7df2_dd67_ddca_097b), // board:d3:white:pawn
                Id(0xea9d_dd74_74cc_6c5b_f377_0dc5_b49f_7f31), // board:d3:white:knight
                Id(0x696a_7102_7a6d_14cd_67b0_acc7_7821_c38f), // board:d3:white:bishop
                Id(0xc46e_8062_dcb7_84f2_d735_0a89_29e5_1d65), // board:d3:white:rook
                Id(0x9d8b_adfc_9b5d_fa8e_a9b6_2288_b7a2_3b04), // board:d3:white:queen
                Id(0x548f_5b76_3d52_9871_9f89_d182_af04_50bd), // board:d3:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x1752_3f4f_147d_2998_0364_0dc0_aa53_255b), // board:e3:black:pawn
                Id(0x316b_c87e_4ac5_dc27_1f0a_60f9_d1a9_2729), // board:e3:black:knight
                Id(0xa89e_1021_efea_c1b9_b587_1358_2b47_33a4), // board:e3:black:bishop
                Id(0x6d1a_e181_3dad_45e4_e034_bcbb_03e1_c2dd), // board:e3:black:rook
                Id(0x6446_9645_dc26_0a1c_6957_ae16_4e6e_06e7), // board:e3:black:queen
                Id(0xd382_2ed8_10a9_a867_4789_70b2_ac7c_48d6), // board:e3:black:king
            ]),
            RoleTable::new([
                Id(0x346e_5fd1_4735_f9b0_66d6_84aa_fb8b_b6f6), // board:e3:white:pawn
                Id(0xd558_386f_4366_d983_78a0_0144_2315_35b2), // board:e3:white:knight
                Id(0x7e0e_d12f_e8b6_6e5a_d7b5_79c6_667c_0644), // board:e3:white:bishop
                Id(0x1852_a2c8_dd1b_6d73_23f0_1f94_6c70_49fe), // board:e3:white:rook
                Id(0x4f39_8588_02c2_fa8c_b7ee_7cbf_1e3d_bad9), // board:e3:white:queen
                Id(0x5bb2_9a2b_b0af_9925_4360_41a3_690c_aa34), // board:e3:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x9397_1dc1_5de0_e8c2_17a6_9407_1963_631f), // board:f3:black:pawn
                Id(0x2739_6289_2e69_a98a_c5e5_217f_98f7_1af4), // board:f3:black:knight
                Id(0x002e_7503_ad4e_6e32_0d52_def2_73c5_29ef), // board:f3:black:bishop
                Id(0x5fd1_c637_bbbe_8e2d_ce9a_a2d4_a8a7_e3bc), // board:f3:black:rook
                Id(0x2da3_b9f3_027a_67ba_493b_f30b_05af_485b), // board:f3:black:queen
                Id(0x2c69_c52d_584a_27ad_4e2a_01db_b7e8_5c5c), // board:f3:black:king
            ]),
            RoleTable::new([
                Id(0x4677_9c32_33be_2a0e_0512_e20a_6a50_95e8), // board:f3:white:pawn
                Id(0xdabd_5b3a_cc0f_74fc_de81_c02b_ac07_ffc2), // board:f3:white:knight
                Id(0x08cf_cd41_67cd_0af1_5078_5f00_17c5_5e63), // board:f3:white:bishop
                Id(0xf521_12fe_3c2b_799c_02e5_d8c5_da16_7468), // board:f3:white:rook
                Id(0x86f0_46f9_59d6_e981_5021_8ecb_9ac1_f98e), // board:f3:white:queen
                Id(0x688d_6c03_4328_4158_363e_2da5_b1fa_6ca0), // board:f3:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xbd14_ac6e_048a_c359_457a_2dcf_489f_a92e), // board:g3:black:pawn
                Id(0xca36_01aa_945d_ccf7_1a85_5956_5049_83d9), // board:g3:black:knight
                Id(0xecc1_63bb_dc7b_b28b_a95c_772a_dd0d_c6b8), // board:g3:black:bishop
                Id(0x31aa_101b_91b9_0dc8_a6c8_7278_f66c_52f1), // board:g3:black:rook
                Id(0xfdb4_5f4c_28a4_a5b7_8ba1_76ae_e078_62e4), // board:g3:black:queen
                Id(0x4ad0_7f30_ecf7_9995_b0f3_7b52_e6c8_0207), // board:g3:black:king
            ]),
            RoleTable::new([
                Id(0x1f60_ed89_2e42_1bff_baea_0087_b9f0_52fa), // board:g3:white:pawn
                Id(0xa8a0_16a4_6428_e0e0_2ac8_9a75_c80a_1ba4), // board:g3:white:knight
                Id(0x47f5_371b_4143_deb8_a095_4d64_c2a4_1b7c), // board:g3:white:bishop
                Id(0x2d47_3369_6065_70d7_63b5_6d27_2061_4b72), // board:g3:white:rook
                Id(0x03d6_5dc8_42bd_a995_3d86_579f_fc14_2dd0), // board:g3:white:queen
                Id(0xdb1b_0bca_53f8_bac6_ee88_1e25_1b1d_c0c4), // board:g3:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x997e_52cc_9fcf_96e7_1171_2f0c_731b_5677), // board:h3:black:pawn
                Id(0x78f3_4570_7e4d_b084_db6a_c8ae_f8f6_46b0), // board:h3:black:knight
                Id(0x915c_b67e_4bb8_c9b3_109d_5e01_c87d_e720), // board:h3:black:bishop
                Id(0xd6d6_f6d7_acce_8836_4e1e_07d4_9c2a_7972), // board:h3:black:rook
                Id(0x2cc8_0002_8b1c_b654_35bb_2555_b933_a1a5), // board:h3:black:queen
                Id(0x70d7_4d8e_abfe_2a3a_7b13_d3ce_3936_1ff1), // board:h3:black:king
            ]),
            RoleTable::new([
                Id(0xd191_6518_7a56_64b1_f461_d0f7_3267_15d5), // board:h3:white:pawn
                Id(0xf2c3_411b_4ab0_9047_f11d_7820_a590_ed68), // board:h3:white:knight
                Id(0x2378_3fe0_cbb2_127a_f9fe_96ee_dc91_9e17), // board:h3:white:bishop
                Id(0x905d_17f6_2b6c_d0fe_c485_365d_3828_b148), // board:h3:white:rook
                Id(0x5c60_b45b_6b48_8d8c_0d1b_1e18_e6a3_492c), // board:h3:white:queen
                Id(0xb191_25fc_be81_3a29_4581_2382_9611_2839), // board:h3:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x49ef_e2f7_510d_c71a_6ba8_204c_c3ec_129f), // board:a4:black:pawn
                Id(0x62e2_7dde_9eb7_4ea2_7f0d_ab92_4574_fca4), // board:a4:black:knight
                Id(0x2b1e_162a_2e37_c83d_b6e4_c2bd_ad0c_f0fd), // board:a4:black:bishop
                Id(0x5d75_3ded_8e78_b71d_a690_cbcf_171a_b618), // board:a4:black:rook
                Id(0x6ba9_7eb3_ab97_cd06_2dd9_35ec_fe30_0126), // board:a4:black:queen
                Id(0xbbfc_9b9b_145e_bc9c_1eae_decd_9baf_b39a), // board:a4:black:king
            ]),
            RoleTable::new([
                Id(0xa86b_dc61_96f2_fc29_af06_817a_1f7a_d1eb), // board:a4:white:pawn
                Id(0xe0e7_d9fa_36e0_bb51_3ec1_07f4_ee7f_2252), // board:a4:white:knight
                Id(0xb320_57d8_29f9_a010_32e5_afd4_4d50_6811), // board:a4:white:bishop
                Id(0x752b_41e8_0bf3_c7e5_4b5e_02c0_d134_d44f), // board:a4:white:rook
                Id(0x6cc9_eac6_3175_918d_001f_9df5_01d0_adab), // board:a4:white:queen
                Id(0xb27d_008d_8f88_18ec_b3fe_9960_5e42_435a), // board:a4:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x9b5d_a4f7_3b0a_9d9e_914e_1eb7_0869_fac3), // board:b4:black:pawn
                Id(0xf027_736a_7720_08a1_938b_5b01_f569_3c68), // board:b4:black:knight
                Id(0x432d_0569_05fa_471b_16d2_99e8_9d31_5572), // board:b4:black:bishop
                Id(0xf941_94bf_8867_7cf0_07d4_c6a9_72d4_c5e8), // board:b4:black:rook
                Id(0x0c12_89c4_bc79_be08_f1dc_1caa_93ce_bf22), // board:b4:black:queen
                Id(0xeb01_66b7_b649_8205_0742_b9ad_09d8_0719), // board:b4:black:king
            ]),
            RoleTable::new([
                Id(0x8fb8_c5a2_5804_860f_2db6_d92c_5ce6_1319), // board:b4:white:pawn
                Id(0xc5e1_100a_c723_1589_59d2_0cdc_a0b2_490a), // board:b4:white:knight
                Id(0xec6a_8b9e_512e_3d48_955a_d5bb_c67b_1e98), // board:b4:white:bishop
                Id(0xcf7d_2c79_b799_f690_79f4_b5a9_f7d5_7229), // board:b4:white:rook
                Id(0x46c1_4296_c3e1_6cff_5bd3_eca6_bfb4_20fc), // board:b4:white:queen
                Id(0xa45d_b458_cdb3_130e_1cb5_d561_1471_1ab5), // board:b4:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x3625_a404_8df6_3f25_00ab_c424_a54c_8003), // board:c4:black:pawn
                Id(0xadb8_d773_cbc2_7990_adcd_fcc1_b771_5b2c), // board:c4:black:knight
                Id(0xc311_7753_e3e9_4d16_0f9e_c9aa_1b74_bfea), // board:c4:black:bishop
                Id(0xe543_0bfb_c16c_9594_a3ac_d6ab_5ebf_8001), // board:c4:black:rook
                Id(0x0440_61a3_72fc_83ce_175b_6606_49f2_863e), // board:c4:black:queen
                Id(0x5224_561b_d57f_69ab_4b9e_63ac_9624_5568), // board:c4:black:king
            ]),
            RoleTable::new([
                Id(0x9c62_a4a7_ea0b_9f07_854e_c476_da77_811c), // board:c4:white:pawn
                Id(0xb849_9eae_327f_a679_6366_4be0_5ef6_9464), // board:c4:white:knight
                Id(0xd600_aab4_6c62_5296_64b3_1260_3476_bda4), // board:c4:white:bishop
                Id(0x68f9_d345_8c38_6cf1_9041_0fa5_4a52_fea6), // board:c4:white:rook
                Id(0xbf62_e7eb_73e0_ad0e_d737_69b6_f59b_e925), // board:c4:white:queen
                Id(0xca1f_6b34_078a_8ba1_5db4_72e0_e40f_2a34), // board:c4:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x274e_8b9a_e309_f8c0_0510_f0f7_0bb6_8781), // board:d4:black:pawn
                Id(0xc5f7_38fb_963f_dd40_4960_1c1c_3f5e_72a7), // board:d4:black:knight
                Id(0xece5_d1e9_548b_6ed5_02c6_b015_3aef_47b8), // board:d4:black:bishop
                Id(0x05d9_163a_68fa_ac00_0a5e_0819_14a3_15cf), // board:d4:black:rook
                Id(0xbb36_4ea9_41c9_74de_ee29_58df_51a1_8e2b), // board:d4:black:queen
                Id(0x622f_305c_2f55_e787_0d1b_166b_ac09_9294), // board:d4:black:king
            ]),
            RoleTable::new([
                Id(0xdfc7_13c7_77ac_f560_6905_c98e_92bd_f353), // board:d4:white:pawn
                Id(0xd88c_4921_a1da_1dfa_e4a7_844b_1f8d_cf7e), // board:d4:white:knight
                Id(0xf4ae_bfa7_e10d_b906_1431_2abe_fd30_7d68), // board:d4:white:bishop
                Id(0x8ae4_9c1d_04cf_5b4a_81b4_7ee1_d12a_6874), // board:d4:white:rook
                Id(0x61de_362b_d8a7_4ac3_a3fa_68db_0fb3_1269), // board:d4:white:queen
                Id(0xd9d4_0132_487b_353f_f55f_77a1_7ed3_fbec), // board:d4:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xc2f2_3364_758a_ffbd_38a3_ca02_3e19_75d4), // board:e4:black:pawn
                Id(0x597d_ad6c_f86c_c8ab_c748_ba50_75e0_6b84), // board:e4:black:knight
                Id(0x68ca_a02a_5cf9_14df_8668_eca7_40d9_d24b), // board:e4:black:bishop
                Id(0xd870_05a2_7298_cd7b_99d8_ee07_f570_f89c), // board:e4:black:rook
                Id(0xbcbb_f3d8_3044_1701_72b7_6ac0_30d0_7446), // board:e4:black:queen
                Id(0xcd4e_a5e3_ce11_4e86_203b_4aea_afce_3eba), // board:e4:black:king
            ]),
            RoleTable::new([
                Id(0x2a31_0396_05a0_4aa1_179b_7e35_20a3_dd87), // board:e4:white:pawn
                Id(0x4ffe_0d69_f335_885b_ef89_88c9_5b6c_c96a), // board:e4:white:knight
                Id(0xbb28_0ed6_b389_5550_ceb3_8203_1156_99da), // board:e4:white:bishop
                Id(0x92f8_0f06_e219_674b_e4fa_802b_4de9_3195), // board:e4:white:rook
                Id(0xc8cf_2bfa_fde0_264b_a88d_f537_e33e_62ea), // board:e4:white:queen
                Id(0x7e68_9aad_d4d6_fc16_adbf_afa7_9a77_a70b), // board:e4:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xafec_51de_6b2e_cdd2_e305_941d_c53a_caed), // board:f4:black:pawn
                Id(0x0701_59e7_35bf_c2e8_72b7_7ac1_9658_0dd2), // board:f4:black:knight
                Id(0x67c8_3f13_f215_c7e0_54b1_677d_b6f7_249d), // board:f4:black:bishop
                Id(0x9f4b_da4b_2665_8043_fcef_b432_01a1_e327), // board:f4:black:rook
                Id(0xc97f_fe28_2c34_0446_3b46_0394_e37a_6c37), // board:f4:black:queen
                Id(0xdc73_c5f6_446c_7e64_f32d_63e1_a4be_19f8), // board:f4:black:king
            ]),
            RoleTable::new([
                Id(0x53ed_fe38_a08b_582f_3e4e_62c0_43da_2a92), // board:f4:white:pawn
                Id(0x052d_5239_eae6_d700_8b03_fb89_d89f_4efb), // board:f4:white:knight
                Id(0xfca2_75c8_f236_2e01_2094_5e50_ed96_de33), // board:f4:white:bishop
                Id(0xb0f1_3fc5_dccd_fe30_3a0d_2c19_54cf_c5d1), // board:f4:white:rook
                Id(0xd454_2d65_5c8b_9500_f7c4_2d42_8c0e_28c4), // board:f4:white:queen
                Id(0x59f6_5570_d938_38bc_0243_c062_4cd1_8d17), // board:f4:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x5ab0_63a2_67a1_be3a_f115_0c5e_84ba_f1ac), // board:g4:black:pawn
                Id(0x89ee_9c72_24ea_fcaf_c38a_a611_c4ac_aec9), // board:g4:black:knight
                Id(0x6aa8_df03_7dc4_3885_e02f_8d9a_aafa_d486), // board:g4:black:bishop
                Id(0xc087_ebb9_d356_c3ac_ebb7_6031_d7a1_43ec), // board:g4:black:rook
                Id(0x4261_ddb8_c3af_4584_58b0_4ef3_2ee2_d322), // board:g4:black:queen
                Id(0x505f_f2ea_2cd9_a0e1_bea4_b18c_734d_89ec), // board:g4:black:king
            ]),
            RoleTable::new([
                Id(0xdbe3_7b1a_d0a1_432d_8f9f_e136_9202_9703), // board:g4:white:pawn
                Id(0x88b6_3dfc_1eb3_9372_022f_14ae_112d_03db), // board:g4:white:knight
                Id(0xd829_82ea_2926_9f5c_0542_5180_5d0b_d61b), // board:g4:white:bishop
                Id(0x3b21_1b8d_0b98_4368_a4c4_5eda_2a66_bbc0), // board:g4:white:rook
                Id(0x714f_acd5_0613_f69e_eea8_9f6a_aca4_6b02), // board:g4:white:queen
                Id(0x0905_4cac_8505_ee0c_62a8_df44_3023_4cf5), // board:g4:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xa79f_11d4_7ba4_9604_4c74_955a_1c55_e74f), // board:h4:black:pawn
                Id(0x83f3_d171_b0f0_52b4_9bee_3f7b_992e_2035), // board:h4:black:knight
                Id(0xb456_345e_f4fb_187f_b865_1e61_79ca_5623), // board:h4:black:bishop
                Id(0x9c09_19f8_beb8_6867_7e48_b16b_e665_9c53), // board:h4:black:rook
                Id(0x45f9_d46b_a242_adf0_a6bd_62a4_7996_a911), // board:h4:black:queen
                Id(0x419a_9552_e68c_d90f_3901_f900_e89c_6dcb), // board:h4:black:king
            ]),
            RoleTable::new([
                Id(0xd205_e884_2db2_d4f4_b025_96a4_1f6a_e727), // board:h4:white:pawn
                Id(0xa5e1_4c1b_9eb6_3692_ef8f_df01_e748_598e), // board:h4:white:knight
                Id(0x47c9_1f8a_6784_cad5_75f3_e933_e948_e4c5), // board:h4:white:bishop
                Id(0xf2cb_1eee_c287_f87a_3c5a_f273_87b6_15a0), // board:h4:white:rook
                Id(0x243c_7807_10c3_f44d_c499_3998_5937_7189), // board:h4:white:queen
                Id(0x3196_acff_cb9f_695c_6b64_f3d3_44ca_9b59), // board:h4:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x757b_8918_0569_90c7_5e6c_b370_2cd1_a7f7), // board:a5:black:pawn
                Id(0x80f7_b5e3_f9da_8de5_043f_7b04_9edc_9cdb), // board:a5:black:knight
                Id(0xabd9_90ff_4daf_8e69_f977_f5c1_c606_b663), // board:a5:black:bishop
                Id(0xb0a0_6497_070b_6451_e6d3_4af6_8553_76c3), // board:a5:black:rook
                Id(0xc751_7167_fc06_3f3a_3ce8_eae7_6969_2ca4), // board:a5:black:queen
                Id(0x5623_3cde_8866_f2f9_5694_3bb9_47b0_81f2), // board:a5:black:king
            ]),
            RoleTable::new([
                Id(0xc153_4d47_dbf4_6eee_2296_d737_6169_2b33), // board:a5:white:pawn
                Id(0x857e_5287_e095_1e7e_98e9_f5ea_e50d_d884), // board:a5:white:knight
                Id(0xde2b_2f74_9291_23b1_db9c_73c3_3c9a_1055), // board:a5:white:bishop
                Id(0xe8a4_4504_25cf_eaa9_00b0_647c_704e_d465), // board:a5:white:rook
                Id(0xcc0e_59b9_cfbd_98a4_8c31_deee_a11f_cd0d), // board:a5:white:queen
                Id(0x288d_42ce_dcb9_3f9b_7503_bc4c_ee83_9031), // board:a5:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xa5ba_c0bf_59ef_18a2_a067_1c16_9df4_d6a6), // board:b5:black:pawn
                Id(0x2ff1_2d32_9c31_9766_9198_f540_4062_026d), // board:b5:black:knight
                Id(0x0ac1_79f9_48ab_cc69_8235_1af0_d4ff_dd49), // board:b5:black:bishop
                Id(0xe996_deff_cb45_2781_bb18_a529_087a_7555), // board:b5:black:rook
                Id(0xb930_704e_5afe_1321_4362_6cb0_fcbd_93af), // board:b5:black:queen
                Id(0x25d7_d06e_2604_8094_11b5_f31d_840c_ab59), // board:b5:black:king
            ]),
            RoleTable::new([
                Id(0x4d1e_daf0_0eb8_d375_c994_39ee_9dda_0fe4), // board:b5:white:pawn
                Id(0x828d_2dd8_19e1_e9e9_b5a3_e126_296e_8f43), // board:b5:white:knight
                Id(0xe6d7_4f1f_7564_65e9_d775_e9c4_d5f6_3910), // board:b5:white:bishop
                Id(0x85dd_aa6b_4590_7424_aa08_3b5d_809c_14ab), // board:b5:white:rook
                Id(0xcd3a_8da3_06c4_1f26_3934_dfe5_fe2a_f94a), // board:b5:white:queen
                Id(0x3872_26ef_1a87_87f0_b0c3_4a97_433d_4f32), // board:b5:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xddc1_bfd1_a34c_0ae1_6cd5_fe21_8adf_d520), // board:c5:black:pawn
                Id(0x8c3b_b557_7b30_65d7_794d_cfe4_3430_1ed4), // board:c5:black:knight
                Id(0x1296_61ff_d5b7_24a4_8cce_339f_f155_e3f3), // board:c5:black:bishop
                Id(0x58b0_4a71_b2a3_4fc9_2e4c_03e7_a8c9_8392), // board:c5:black:rook
                Id(0x5379_5aac_15d4_80ec_554d_96ca_384e_029b), // board:c5:black:queen
                Id(0x446f_ac69_c9f4_ab02_1d21_1810_840b_b699), // board:c5:black:king
            ]),
            RoleTable::new([
                Id(0xb629_c9e9_e19a_86b7_0368_5166_ee83_95e0), // board:c5:white:pawn
                Id(0xe450_0ac9_1497_65b4_a571_32c2_9aac_d0b1), // board:c5:white:knight
                Id(0x5fb6_d919_7849_4ef8_c2ea_4aa8_eeb0_a2ad), // board:c5:white:bishop
                Id(0x016f_4f21_82e2_692f_ece3_f13b_5b5e_24f8), // board:c5:white:rook
                Id(0x7604_45e5_b285_832d_c56a_6075_b5cf_1381), // board:c5:white:queen
                Id(0x70cd_3f5f_4cdd_9d62_2fc3_1f65_49a3_f6d1), // board:c5:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xabac_543f_c49d_facb_e58d_c2a6_c664_b947), // board:d5:black:pawn
                Id(0xc2dc_e0be_1938_317a_ddcd_159d_d0df_8344), // board:d5:black:knight
                Id(0x0810_c202_6926_a4b7_d1ee_dec0_5190_5775), // board:d5:black:bishop
                Id(0x1cad_6471_1000_98e2_4429_7c8a_521e_207d), // board:d5:black:rook
                Id(0xcbca_cdf9_1935_8feb_be3e_97da_e9e6_7121), // board:d5:black:queen
                Id(0x75fa_0e51_4a5c_38a3_8272_ee20_7332_40eb), // board:d5:black:king
            ]),
            RoleTable::new([
                Id(0x1210_16a4_f9ea_033b_f6b8_b283_bbfa_a0c0), // board:d5:white:pawn
                Id(0xc754_cff8_199a_d27f_014d_c5d7_1efe_5598), // board:d5:white:knight
                Id(0x1ba7_cfb1_e7b7_9ff7_290c_fc4f_8549_35de), // board:d5:white:bishop
                Id(0x2f64_6529_bd6d_e702_6595_ef77_79e9_c090), // board:d5:white:rook
                Id(0xb673_491f_6042_103b_606b_a65d_ee51_b924), // board:d5:white:queen
                Id(0x0191_23dd_738a_94f1_a506_7e56_fe5e_ff17), // board:d5:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x65d6_4d79_d900_f05b_a65f_1aab_4918_54d2), // board:e5:black:pawn
                Id(0x3303_0f83_d7b5_5a73_57b9_75b4_d048_d4fc), // board:e5:black:knight
                Id(0xc090_2c71_96a0_8253_7875_e659_75f4_32a2), // board:e5:black:bishop
                Id(0x69ba_eacd_757b_6383_36e9_6510_bc88_fda0), // board:e5:black:rook
                Id(0x9d83_a1ad_9925_040a_4392_93bf_036a_59e5), // board:e5:black:queen
                Id(0x4750_ac9f_ecb7_a505_03f4_070a_66d2_f516), // board:e5:black:king
            ]),
            RoleTable::new([
                Id(0xea8b_4246_b558_3147_4bcb_69eb_a852_7d84), // board:e5:white:pawn
                Id(0xd1ae_fdfb_8d70_78af_243a_463e_8cac_e6d5), // board:e5:white:knight
                Id(0x6517_99d1_03dd_3247_9729_78f5_7558_cd39), // board:e5:white:bishop
                Id(0x73b1_ff60_9a10_b22d_3982_ee22_18f0_8abc), // board:e5:white:rook
                Id(0xcc6a_9205_3645_e4a3_bc76_b22e_615b_d093), // board:e5:white:queen
                Id(0x68a3_e0fe_b971_35cc_3bbf_efb6_4f3e_2761), // board:e5:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x535d_cc50_f2d3_cbe9_626a_401d_f3d3_deb7), // board:f5:black:pawn
                Id(0x9c48_4e4e_bc2f_91fa_f28f_fd08_f0a7_4a43), // board:f5:black:knight
                Id(0x02f4_8b23_2205_585d_778c_2fd6_f854_e078), // board:f5:black:bishop
                Id(0x70e2_3652_c5f5_aef7_1eef_dfb1_6cae_1bb1), // board:f5:black:rook
                Id(0x5573_a9c6_41ff_4cd1_7263_ab6e_81e3_a6c5), // board:f5:black:queen
                Id(0xa2eb_5b0e_2555_d1a2_1c29_7c6e_b848_afe1), // board:f5:black:king
            ]),
            RoleTable::new([
                Id(0x1b65_d8c5_014a_26ed_03ff_267c_ac13_21dd), // board:f5:white:pawn
                Id(0xecd8_2b23_4884_0ed0_3de0_9d72_7b89_b06c), // board:f5:white:knight
                Id(0xd605_b968_6818_3418_48bc_be0e_1902_d60a), // board:f5:white:bishop
                Id(0x097d_0b46_0022_dcd8_e2ca_f7c0_df67_6e08), // board:f5:white:rook
                Id(0x43ff_7688_bd2d_1b91_f8d0_cf0e_926b_3a5a), // board:f5:white:queen
                Id(0xd37a_ec38_e53e_725c_b7c6_1c4d_46c4_75d1), // board:f5:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xa409_2a2a_9dff_b555_0080_6769_b1f1_fbeb), // board:g5:black:pawn
                Id(0xc8bd_89bf_a371_d15d_111b_36a7_29e2_9e8f), // board:g5:black:knight
                Id(0xd3f8_4251_d71e_eb9d_bdd6_5a1a_2f83_8202), // board:g5:black:bishop
                Id(0x6570_0880_04e3_b5ac_dbf3_64c2_0561_2e1e), // board:g5:black:rook
                Id(0x46d9_b752_6bfe_004e_2c6a_034f_9c35_dec5), // board:g5:black:queen
                Id(0xbc7d_0d6a_6f8b_d62c_4f40_1ada_ef83_6978), // board:g5:black:king
            ]),
            RoleTable::new([
                Id(0xf3ff_b073_0b35_e241_2d8a_c647_4fe5_dbcd), // board:g5:white:pawn
                Id(0xd9cc_652a_dee0_ed1c_8f0e_4f65_554c_4bcc), // board:g5:white:knight
                Id(0xd79f_2b52_b244_3822_f915_ff15_0b77_8b8d), // board:g5:white:bishop
                Id(0xed0a_b343_d8f5_be63_5d4b_adc0_8314_4e41), // board:g5:white:rook
                Id(0xd728_f355_9d96_5caf_a867_9100_1e72_141f), // board:g5:white:queen
                Id(0xd3bd_9778_0ab2_1854_7dcf_be79_2422_b5e7), // board:g5:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xb712_adbb_2709_53a8_694e_cc8a_497a_b1d6), // board:h5:black:pawn
                Id(0xcb34_9119_b84b_88ec_2596_ca7d_4421_761d), // board:h5:black:knight
                Id(0xc127_e15d_efa2_b3a6_2f3f_1f91_1f79_c8cd), // board:h5:black:bishop
                Id(0x6149_5590_f191_6824_63b2_4321_8c1e_3da0), // board:h5:black:rook
                Id(0x98f7_1f62_2d18_816c_869b_3f7e_9e5f_238b), // board:h5:black:queen
                Id(0x6615_8752_d8da_af96_9c88_f6a8_19f9_7f41), // board:h5:black:king
            ]),
            RoleTable::new([
                Id(0xaa48_d23e_6a22_c399_5263_e43f_6d6c_5560), // board:h5:white:pawn
                Id(0xddb0_ab7f_5a51_d6b2_51e6_9fec_8baa_8786), // board:h5:white:knight
                Id(0xfe86_e86f_ed78_9e2d_7769_30fa_7be1_0114), // board:h5:white:bishop
                Id(0xae7e_6936_7032_f890_5829_23d2_d5a8_c4d7), // board:h5:white:rook
                Id(0x65f5_f660_d0e3_f2d4_1ee3_74ae_f57b_5f9c), // board:h5:white:queen
                Id(0xa0de_2e9f_232e_4b8a_9d69_ad6b_ed6f_1a0c), // board:h5:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x9b22_da1c_d848_783b_469e_366c_ccd7_96b0), // board:a6:black:pawn
                Id(0x24b4_6c34_84f1_647c_1649_231b_bccc_bf49), // board:a6:black:knight
                Id(0xc0d4_1f6b_fd93_4872_56ca_fe93_584b_e52e), // board:a6:black:bishop
                Id(0xf96d_6838_15e3_a60f_cb2a_cac2_1081_fcda), // board:a6:black:rook
                Id(0x273a_1310_1369_a0d0_14ac_33b1_7f43_5363), // board:a6:black:queen
                Id(0xf967_3284_9b7c_2518_8249_888d_b00a_ce71), // board:a6:black:king
            ]),
            RoleTable::new([
                Id(0x4a33_61dd_fc4f_e838_8fa5_eb8d_fe24_b7f1), // board:a6:white:pawn
                Id(0x352f_d327_f70f_952e_a429_4268_c88f_4101), // board:a6:white:knight
                Id(0x3495_599a_790d_89a5_c9d0_90b7_4f43_918a), // board:a6:white:bishop
                Id(0xf1bd_2f1e_7753_e5dd_fc12_92d9_4813_7d7d), // board:a6:white:rook
                Id(0xbbf4_c5aa_301c_b1db_658a_5747_1737_29c2), // board:a6:white:queen
                Id(0x9a92_42f8_0f7c_c812_0254_8960_c987_b152), // board:a6:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x5f7d_c252_bb5b_e51f_5225_144f_fa14_3b0a), // board:b6:black:pawn
                Id(0x97c8_91a5_4cde_87c1_c6ee_bd9a_3d5e_3a74), // board:b6:black:knight
                Id(0x5ced_abb6_5b36_6429_31f7_b57b_5bd6_19f6), // board:b6:black:bishop
                Id(0xc282_ca03_898b_fadf_5e4f_a519_ce0e_f324), // board:b6:black:rook
                Id(0x35ec_1fa6_df8e_bc3f_cf71_5369_6ff0_cace), // board:b6:black:queen
                Id(0xf575_be01_81af_d627_a067_fb21_e1c8_92c1), // board:b6:black:king
            ]),
            RoleTable::new([
                Id(0xf3ec_21e0_7f2b_a6c6_62da_a7b6_433c_4f5d), // board:b6:white:pawn
                Id(0x3d8c_69e4_0df3_6098_0b05_69d8_0cd7_1c4e), // board:b6:white:knight
                Id(0x1925_3487_7a67_471a_de94_a574_83c1_2c08), // board:b6:white:bishop
                Id(0x4483_7984_b365_b9a0_6bfd_a933_c273_beed), // board:b6:white:rook
                Id(0x4cd4_7f95_a566_cd94_ec40_bce6_21de_58f0), // board:b6:white:queen
                Id(0x4a65_13e2_e07b_64f4_7947_eaa3_8edc_dc8e), // board:b6:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x9357_de55_98c8_355f_1e87_0c90_1622_0106), // board:c6:black:pawn
                Id(0x755f_b9ea_576b_df4f_0277_ff88_5f63_1816), // board:c6:black:knight
                Id(0x89be_40be_abe6_c3bf_c050_63a0_9836_d7bb), // board:c6:black:bishop
                Id(0x7595_f218_a9c5_c3f9_df91_1bf8_eedf_67f7), // board:c6:black:rook
                Id(0x5088_d1dd_8329_9284_ec47_99f7_a846_269b), // board:c6:black:queen
                Id(0xfbf4_a576_05aa_9e60_2bcb_e9c9_1994_c5f5), // board:c6:black:king
            ]),
            RoleTable::new([
                Id(0x9496_c0fe_a89f_6924_2087_cbb1_702b_d705), // board:c6:white:pawn
                Id(0x2580_43dc_08f4_663d_5db7_82a2_818e_f60e), // board:c6:white:knight
                Id(0x0038_3f6e_7cba_b85d_52da_b61f_a016_3965), // board:c6:white:bishop
                Id(0xdde5_3c01_3589_323f_7f0c_d1eb_3bf1_2dac), // board:c6:white:rook
                Id(0x44e3_d767_50c6_3199_fbf8_bbe2_8c76_0864), // board:c6:white:queen
                Id(0xfa2c_f928_1f8d_d8fd_9312_4476_c669_12f3), // board:c6:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x3ab6_5713_d41c_74f2_2f56_e6f4_a377_540a), // board:d6:black:pawn
                Id(0xefa8_3beb_2508_aaca_c8ce_99ed_a785_6d09), // board:d6:black:knight
                Id(0xc144_8926_d982_d6fa_6d4b_3760_3486_1017), // board:d6:black:bishop
                Id(0xbc20_c2cb_52d0_4511_9121_4606_7849_b7b8), // board:d6:black:rook
                Id(0x89c8_3e88_3b64_8d2e_8d2f_3a1f_297d_af15), // board:d6:black:queen
                Id(0x1d5a_a915_2a4e_7607_4df9_6adf_5d64_e91b), // board:d6:black:king
            ]),
            RoleTable::new([
                Id(0x3696_b20d_830c_d959_5b2e_1879_0630_0dd0), // board:d6:white:pawn
                Id(0x9593_2ac4_999e_b4ba_a32c_cabd_06f2_4092), // board:d6:white:knight
                Id(0xbc6e_d8c7_b954_3088_3ef0_c628_942e_bdb6), // board:d6:white:bishop
                Id(0x39d9_a49e_45d3_712e_0506_7951_1e4c_bf03), // board:d6:white:rook
                Id(0x3d58_6acd_1c56_bd0a_3fa0_3a58_368a_3e42), // board:d6:white:queen
                Id(0xda83_7489_6feb_f040_5cb7_56ba_9cba_9e0f), // board:d6:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x2a5a_2e16_5ec0_e8c8_89e7_e9cc_dc2b_427a), // board:e6:black:pawn
                Id(0xac59_15ab_f459_d106_f5fa_ff6d_d98b_86da), // board:e6:black:knight
                Id(0x3525_a9e7_d516_9cb2_d20c_9b0e_976b_455c), // board:e6:black:bishop
                Id(0x11ce_789e_5b31_e635_8c1d_be5b_ccb4_808a), // board:e6:black:rook
                Id(0xfce5_af61_9975_2704_0a38_ca16_6d4b_6bf9), // board:e6:black:queen
                Id(0x831c_6b8c_e1a4_1be0_7604_e123_bfec_8c4f), // board:e6:black:king
            ]),
            RoleTable::new([
                Id(0x2208_8cbc_c8ed_19b0_f1a1_d351_06e2_c163), // board:e6:white:pawn
                Id(0x3358_3979_b924_a310_df57_7c6a_2a28_2943), // board:e6:white:knight
                Id(0x0a7e_a93b_0ff7_90bc_cda4_7468_2bfd_91e5), // board:e6:white:bishop
                Id(0x2587_9c28_7ad9_a031_a04e_c20d_e305_ea28), // board:e6:white:rook
                Id(0xe898_8af6_efed_7fd4_b68a_e151_6df7_73a9), // board:e6:white:queen
                Id(0x532c_4d02_f85e_e98f_c5dc_0c13_07ae_9401), // board:e6:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x905a_c739_4189_386c_4797_e307_f093_23e2), // board:f6:black:pawn
                Id(0x688b_b0ab_2bff_494b_2cc5_5740_9737_c5fc), // board:f6:black:knight
                Id(0x83e0_f031_0c4e_649e_e93b_e4c6_e842_9232), // board:f6:black:bishop
                Id(0x84b9_62a8_3c4e_12da_a13a_2b3e_b522_2488), // board:f6:black:rook
                Id(0x5671_5343_81ea_1c55_7012_dfa4_f365_e172), // board:f6:black:queen
                Id(0x6c78_a37c_be2b_9dc0_862e_7ab9_13ae_a041), // board:f6:black:king
            ]),
            RoleTable::new([
                Id(0x91a7_9b6c_5c83_9d8b_a4bc_15ef_800f_66d7), // board:f6:white:pawn
                Id(0xd1a9_a35d_67ce_3297_1e04_14c8_ea5b_e595), // board:f6:white:knight
                Id(0x8624_95c6_a6c0_8c01_b982_33f7_4074_f478), // board:f6:white:bishop
                Id(0x73be_303f_c863_d43a_8f89_a9c3_88b9_0665), // board:f6:white:rook
                Id(0x0b5e_796b_88bb_6868_b383_a897_0731_cad0), // board:f6:white:queen
                Id(0xbffd_466b_6f71_c05d_a36d_81b1_f4ec_2da4), // board:f6:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x2296_378e_adf2_bbc0_96f6_7318_edfc_b384), // board:g6:black:pawn
                Id(0xb4b1_e7a7_7c4b_eabd_7017_6b50_a7b0_6f47), // board:g6:black:knight
                Id(0x0ae6_dafd_9980_1040_e713_17eb_cec7_a13b), // board:g6:black:bishop
                Id(0x4aa6_7abb_60aa_306b_388a_e402_b5b6_c5c1), // board:g6:black:rook
                Id(0x152b_5638_e6f7_9158_edda_6513_da09_9cd4), // board:g6:black:queen
                Id(0x7473_2968_5bd0_37e3_6f15_e0b1_6995_e2f7), // board:g6:black:king
            ]),
            RoleTable::new([
                Id(0x6214_62c2_e4a8_1047_90c4_9218_96b9_442f), // board:g6:white:pawn
                Id(0x526c_1268_d6d0_b912_a865_126b_31b8_fae8), // board:g6:white:knight
                Id(0x5a40_6b1f_bb9d_c3eb_8b3a_d188_ea9a_3130), // board:g6:white:bishop
                Id(0xbfb2_c4d5_c335_abc7_cf3f_2194_274d_93fb), // board:g6:white:rook
                Id(0x0d68_f2c2_415c_ac98_bc16_5cf8_c5af_5236), // board:g6:white:queen
                Id(0x4e4f_55ad_3921_16a3_eb37_679d_39a3_96b6), // board:g6:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x9e8d_12a6_63b2_669d_4f39_40ee_2dd1_a651), // board:h6:black:pawn
                Id(0xc423_1374_ac3d_5045_a807_7acf_b81e_8a88), // board:h6:black:knight
                Id(0x31f8_d9a6_126b_28a5_e97d_7bfc_11ce_c2dc), // board:h6:black:bishop
                Id(0x66ae_622b_36b9_b924_f2e9_9612_4923_325e), // board:h6:black:rook
                Id(0x0f2c_2547_3247_74af_565f_6814_8a6c_3dbf), // board:h6:black:queen
                Id(0x9e16_5638_1727_e818_001d_e7b8_0032_7469), // board:h6:black:king
            ]),
            RoleTable::new([
                Id(0x72d0_2171_b591_d823_3a88_dd1c_ecc5_67ed), // board:h6:white:pawn
                Id(0xa887_44de_5245_fd9e_9551_ca98_bdca_590d), // board:h6:white:knight
                Id(0x50d0_607a_305c_a58f_f804_ed28_96fb_73ce), // board:h6:white:bishop
                Id(0x7a22_9e4e_8e86_cf03_8c3a_c204_c4f7_4c9c), // board:h6:white:rook
                Id(0x5faf_3731_de0e_001f_bc0c_8e9a_ef45_4f1a), // board:h6:white:queen
                Id(0x1830_49ed_c20a_ea7e_3c90_1f56_e58c_3f18), // board:h6:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x3932_d171_03a7_4ad9_0884_fc24_a5cc_57d8), // board:a7:black:pawn
                Id(0x7efe_b388_bf2d_83fd_d151_6d34_3225_6110), // board:a7:black:knight
                Id(0x970d_2b16_2f45_60df_2a67_8f07_0320_46c3), // board:a7:black:bishop
                Id(0x678b_a98a_9aad_5814_89b1_bbdc_8c9d_e9dc), // board:a7:black:rook
                Id(0xa4f0_a61c_8cfe_5f34_e12c_ae97_b4c3_4fe1), // board:a7:black:queen
                Id(0x82b2_6858_8901_ef02_d802_3f5a_0880_dd6c), // board:a7:black:king
            ]),
            RoleTable::new([
                Id(0xbef2_96db_aac2_b509_6c9e_d54b_0f10_af5c), // board:a7:white:pawn
                Id(0x23e4_f37a_f1a9_0480_cbfb_c851_afbd_d461), // board:a7:white:knight
                Id(0x5301_f301_4d4d_44df_d06f_ad6c_012f_4cac), // board:a7:white:bishop
                Id(0x9812_1494_39bd_8981_77f2_bda4_4d60_ae61), // board:a7:white:rook
                Id(0x68ad_f540_16d7_bcd2_b344_bcef_e2af_e094), // board:a7:white:queen
                Id(0x7e77_fd24_d43c_3d8b_cfc0_115c_c662_8b9e), // board:a7:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x355e_e12c_444e_97f9_7698_6554_2baf_e58f), // board:b7:black:pawn
                Id(0x6ae3_8a54_185a_8365_fe10_e78f_0810_67b3), // board:b7:black:knight
                Id(0x4e13_b5c6_6ec7_63fb_0764_76e9_4b7c_3f36), // board:b7:black:bishop
                Id(0xd751_f162_23fa_915d_82f9_539a_b4c4_69d7), // board:b7:black:rook
                Id(0x3707_c674_500a_e43a_c5d8_e7e3_b2de_2d8e), // board:b7:black:queen
                Id(0x20ad_1476_e862_48ab_a5c9_5ebd_f487_f020), // board:b7:black:king
            ]),
            RoleTable::new([
                Id(0x27ac_4c64_4a8f_6ed3_c52e_3834_b819_8166), // board:b7:white:pawn
                Id(0x9376_837f_82d6_1208_112f_0246_6d88_0ea3), // board:b7:white:knight
                Id(0x7cd9_3364_97fe_affc_2cd8_7c21_6c0d_088f), // board:b7:white:bishop
                Id(0x13f2_33d5_0d4d_9877_5eca_6ac5_d667_1d2a), // board:b7:white:rook
                Id(0x2025_1133_c70d_04b9_6597_1779_2a40_f2a8), // board:b7:white:queen
                Id(0x4d26_defb_53bd_a59b_6888_ce9d_a9b7_9b0b), // board:b7:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xb2a2_7fc9_ce67_d218_e319_89f1_0034_bb6b), // board:c7:black:pawn
                Id(0xf911_7006_8c9e_8988_8efa_039d_0668_4f25), // board:c7:black:knight
                Id(0x5e34_a36d_27f5_7c47_b896_c2c6_3fbe_8349), // board:c7:black:bishop
                Id(0x53ff_1841_0a8a_62bc_2ffd_db78_2a56_7ef3), // board:c7:black:rook
                Id(0x5a7d_7832_2d65_5fee_6879_40eb_2a90_2adb), // board:c7:black:queen
                Id(0x1613_a659_bb0c_0f57_d235_4fed_ef1d_d2da), // board:c7:black:king
            ]),
            RoleTable::new([
                Id(0x0cb3_6ef0_627c_60d8_4d28_eb09_a906_ac17), // board:c7:white:pawn
                Id(0x949c_08f0_cdac_0822_4679_684a_de2b_0f2f), // board:c7:white:knight
                Id(0xf62d_6b54_d448_a732_e7e6_ee6b_b20c_060c), // board:c7:white:bishop
                Id(0x10c5_525e_70df_bb95_2175_c244_dba5_7ff9), // board:c7:white:rook
                Id(0xe7c7_7fc6_4712_35ef_338f_7499_ea9a_1bc9), // board:c7:white:queen
                Id(0x16fc_0e2f_2ae5_0fd2_4bb1_f4ef_ac39_86a7), // board:c7:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xc85f_176a_ebe2_12c0_7814_7417_581b_b80c), // board:d7:black:pawn
                Id(0x6b04_ea21_ca9a_cc22_7f99_5224_c90e_b458), // board:d7:black:knight
                Id(0xb9c7_f9d8_ce95_291e_73cb_bdab_66b3_5df0), // board:d7:black:bishop
                Id(0x2e41_69ad_30cc_5f3f_7d04_4d2d_3499_fa61), // board:d7:black:rook
                Id(0x7de2_908a_5fb2_a535_efc7_3be8_40a0_15a1), // board:d7:black:queen
                Id(0x35e0_3d1a_9fb0_cf0d_514a_4203_1f1c_a6bd), // board:d7:black:king
            ]),
            RoleTable::new([
                Id(0x5a44_d84e_1036_d3e8_9736_cec1_f053_f77d), // board:d7:white:pawn
                Id(0x6a20_aa00_9726_14e1_68fa_f514_741e_83da), // board:d7:white:knight
                Id(0xed84_ad90_4508_853d_9fd8_8e41_fdcf_5cac), // board:d7:white:bishop
                Id(0x4f20_50a1_5f17_42f9_8778_e678_8cf7_4595), // board:d7:white:rook
                Id(0xad71_8b94_2d9a_95f5_96fc_fd7a_8958_048b), // board:d7:white:queen
                Id(0x4581_7397_3a2a_b522_f28f_8a49_e0be_fd89), // board:d7:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xafc7_c46d_3879_ac8e_ded6_03d1_214f_b356), // board:e7:black:pawn
                Id(0xb1e4_5e90_1090_c49f_07ec_b7ca_3977_cfef), // board:e7:black:knight
                Id(0x7761_50f9_5127_0eb0_9b9a_08dc_0ed2_ec76), // board:e7:black:bishop
                Id(0x2e9c_080a_2cee_85b8_4263_0cea_90b0_66e6), // board:e7:black:rook
                Id(0xc1c5_1498_6bd6_8577_097e_0f91_21e1_414f), // board:e7:black:queen
                Id(0x0206_caeb_ec67_56ff_f4c2_1a44_531b_7387), // board:e7:black:king
            ]),
            RoleTable::new([
                Id(0x5742_b57b_e7d0_bba4_fa39_0f28_206b_0845), // board:e7:white:pawn
                Id(0x7607_3da3_3ed6_bf0a_db75_3f72_3ecd_f3b3), // board:e7:white:knight
                Id(0x2028_d08b_42d1_8b52_22b7_5706_e75f_92e0), // board:e7:white:bishop
                Id(0xf0cb_0539_59fd_1e60_9f10_f20e_206f_e44c), // board:e7:white:rook
                Id(0x8077_5efe_155b_4a29_4ae8_26dd_4d84_f64d), // board:e7:white:queen
                Id(0x5015_a0bd_e7ab_0f1b_6057_c243_cc06_7f37), // board:e7:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x04ff_9de5_83e2_ca65_9a30_dedf_7614_de7c), // board:f7:black:pawn
                Id(0xdd70_aa9c_02ef_7c3c_9e50_91f6_0880_a0e7), // board:f7:black:knight
                Id(0xc224_e15d_ad73_3184_b705_c4b4_3209_403d), // board:f7:black:bishop
                Id(0x1287_ff05_193b_e263_839a_bae7_8d2f_9166), // board:f7:black:rook
                Id(0x7cb9_de6d_ec9b_7b2d_1d6d_b600_76bd_2617), // board:f7:black:queen
                Id(0x781f_5adc_fd16_ef50_acad_f9d3_e459_7066), // board:f7:black:king
            ]),
            RoleTable::new([
                Id(0xfea3_381c_a4cc_a0f6_1257_549d_fd80_d36f), // board:f7:white:pawn
                Id(0x8bdb_e219_b8a9_03cc_baf2_ad2c_52b5_f207), // board:f7:white:knight
                Id(0xef49_3988_6dd7_cd80_c13b_d5d3_4e12_6d84), // board:f7:white:bishop
                Id(0x3978_98ac_3ec1_717f_e51e_47d3_cacd_926e), // board:f7:white:rook
                Id(0xb767_3552_56ef_12d0_0798_8873_3365_9a30), // board:f7:white:queen
                Id(0xae4e_5547_e2de_171b_9d04_c806_a772_a3fd), // board:f7:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x90bd_e425_3936_dc2e_88ad_c8c9_012d_73d0), // board:g7:black:pawn
                Id(0x376e_fafc_632f_cee6_d042_a3e4_8494_91fc), // board:g7:black:knight
                Id(0x42dd_98af_9658_a59d_a138_8827_249a_6aba), // board:g7:black:bishop
                Id(0x7fa5_d011_f035_ca20_5214_0e3b_c511_aa50), // board:g7:black:rook
                Id(0x3c0e_8136_3ab8_d250_cf09_ee7e_3fda_c451), // board:g7:black:queen
                Id(0x0c4b_d69b_d2ec_cc8d_61e8_667a_7693_dd1e), // board:g7:black:king
            ]),
            RoleTable::new([
                Id(0xf2b8_6d8a_4c0c_9ca2_5106_d6d7_6b4b_1921), // board:g7:white:pawn
                Id(0xbee4_d63f_f4eb_1567_a2e0_4d7e_87a0_627d), // board:g7:white:knight
                Id(0xf94b_1898_2342_6015_5960_1240_e34e_6a60), // board:g7:white:bishop
                Id(0x9f01_641c_d9c1_c80f_4afd_dd97_37e4_782e), // board:g7:white:rook
                Id(0x53b6_93c5_65bc_3519_c659_3913_5e6f_de71), // board:g7:white:queen
                Id(0x9592_8152_b842_caf0_6d79_b1ef_763f_f2f1), // board:g7:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x99b4_84f4_abcd_e822_179e_3741_0951_0e7f), // board:h7:black:pawn
                Id(0xce62_c16a_f790_fe71_7fc3_1677_765e_5cd9), // board:h7:black:knight
                Id(0x08f4_1a81_a0cf_6e1b_19ba_ac07_7fd3_fea2), // board:h7:black:bishop
                Id(0xc164_7886_2280_3c3b_501a_0e67_d0a9_3c05), // board:h7:black:rook
                Id(0x5928_c5b0_52d2_2e94_1cd0_6b11_a6f4_5bde), // board:h7:black:queen
                Id(0xf209_b1bd_c2ef_d03c_5f74_aa84_e08a_96f8), // board:h7:black:king
            ]),
            RoleTable::new([
                Id(0xfdfd_4c45_13aa_20ac_697d_8ea1_7887_97a9), // board:h7:white:pawn
                Id(0xcfb3_1b57_75e5_e603_621b_766e_d6f6_c91a), // board:h7:white:knight
                Id(0x9612_3353_b3ea_b1f3_2b97_3ceb_f0a0_68a8), // board:h7:white:bishop
                Id(0x42d4_3020_ffc4_0a67_3c62_e88f_efae_a102), // board:h7:white:rook
                Id(0xbfa6_0e8a_69f8_67e9_c3fd_66bb_9fe4_18eb), // board:h7:white:queen
                Id(0x959c_e36b_776f_9266_b925_5397_4f25_3fe0), // board:h7:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xc9d9_cc5e_e76c_c53f_ce53_40de_9fa9_74cc), // board:a8:black:pawn
                Id(0x3b15_f3d2_8d7d_6e26_0d8e_83b5_22ee_5c98), // board:a8:black:knight
                Id(0xd039_4177_f7f8_2366_e352_6689_515e_e037), // board:a8:black:bishop
                Id(0x836f_c888_215a_e60d_c640_1fad_be25_0ea8), // board:a8:black:rook
                Id(0xea78_c8bf_d6a4_04f7_8f7b_6d6c_ba21_f328), // board:a8:black:queen
                Id(0xce62_6eb6_4f1f_1aec_080d_7a03_8cc0_238b), // board:a8:black:king
            ]),
            RoleTable::new([
                Id(0xbec3_4fcf_9989_0c44_532c_5047_24f0_6f76), // board:a8:white:pawn
                Id(0x4ea1_6a38_76c1_f164_2ade_e24f_ff3c_afd1), // board:a8:white:knight
                Id(0x9faf_12f8_d71c_0bdb_077b_86e7_ba81_d7d2), // board:a8:white:bishop
                Id(0xc8c7_a435_9b22_fae1_18f9_828c_ce0c_466b), // board:a8:white:rook
                Id(0x7749_41f1_d0eb_024d_5668_3292_7ea4_d2ec), // board:a8:white:queen
                Id(0x558a_9841_813a_0231_e1bb_aa2e_4f40_2b53), // board:a8:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x8a62_2d88_f13a_f3ec_1d91_92c7_5a18_0063), // board:b8:black:pawn
                Id(0xfcc8_228f_63a7_d3b2_290f_9a5e_ad87_40fd), // board:b8:black:knight
                Id(0x1848_1932_8e6f_3c23_212a_1a97_86e1_2ccf), // board:b8:black:bishop
                Id(0x1228_edb6_c4e5_2ca7_4be4_b7d8_0f79_33dc), // board:b8:black:rook
                Id(0xdb61_9f4e_b009_beb1_00b5_c450_b52e_75d0), // board:b8:black:queen
                Id(0xc0ed_a82f_9910_95b0_6f93_c3f3_1203_da08), // board:b8:black:king
            ]),
            RoleTable::new([
                Id(0xbd6c_7f1a_6ee1_a3c1_fcd9_6400_6a5f_a712), // board:b8:white:pawn
                Id(0x7eb8_368d_868c_d832_50a8_d6c6_6974_6f2a), // board:b8:white:knight
                Id(0x176d_362b_1c6a_b832_94df_a7c9_1784_c31b), // board:b8:white:bishop
                Id(0xb19f_43a9_4c5f_6deb_ab9e_6ed6_e8f9_8877), // board:b8:white:rook
                Id(0x5e83_6876_e39f_35f9_ca24_df93_10af_04a2), // board:b8:white:queen
                Id(0x4a0f_b6d5_8819_be21_e625_febf_1dfe_6d8e), // board:b8:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x75c3_54fc_6ca8_503e_2b9d_74b7_f2dd_aba9), // board:c8:black:pawn
                Id(0x63dd_9111_97c7_f4f5_c980_91b4_bad1_ae72), // board:c8:black:knight
                Id(0xf833_9b59_2263_bd62_df23_3c5f_6005_71fc), // board:c8:black:bishop
                Id(0x85a4_9f21_7de8_56f4_5667_3d00_6cdd_82f8), // board:c8:black:rook
                Id(0x94e8_17ff_cb61_ec72_7827_2e0e_5cdc_aaa9), // board:c8:black:queen
                Id(0x5b87_4e8f_d7bf_4057_32ae_e29b_4bdc_adce), // board:c8:black:king
            ]),
            RoleTable::new([
                Id(0x3259_cc6f_4634_78a3_c253_8cd5_c21a_30c6), // board:c8:white:pawn
                Id(0xd275_64f0_bea1_9600_d2bb_1656_c19d_b009), // board:c8:white:knight
                Id(0xb905_8aa5_9d10_0661_67b0_8ab8_27a7_48e3), // board:c8:white:bishop
                Id(0x5c6f_6436_977a_8f3c_4c83_6e9a_5072_4c23), // board:c8:white:rook
                Id(0xe64c_5a17_9f7d_771e_15ba_24ed_c9fa_0d25), // board:c8:white:queen
                Id(0x4d14_417b_5bff_13d9_eb96_486d_6cb0_ad9e), // board:c8:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xba69_6654_21e6_0bf0_28dc_58fb_48a0_d44d), // board:d8:black:pawn
                Id(0x85c3_ae7b_8970_9249_e8f1_5043_3b18_5494), // board:d8:black:knight
                Id(0x230e_d899_66b8_8737_ae8b_2a55_3878_2e5c), // board:d8:black:bishop
                Id(0x5df8_8eb1_eb2d_5eda_52f6_3948_934d_ea3c), // board:d8:black:rook
                Id(0x847e_e681_f222_301c_5e5b_e8b3_a7b7_b5b6), // board:d8:black:queen
                Id(0x40d0_db6c_656f_5745_12d0_0696_73c8_d231), // board:d8:black:king
            ]),
            RoleTable::new([
                Id(0x71b6_cf0c_462f_3973_6a47_c4f7_0920_6424), // board:d8:white:pawn
                Id(0x53dc_55c5_4d25_cb97_4ca3_844c_4a96_0a69), // board:d8:white:knight
                Id(0x8128_5a0e_9e49_bea0_7039_03e5_cccb_0a36), // board:d8:white:bishop
                Id(0xdb94_ebd7_2eb4_07c5_5aa9_a307_d6a8_83d2), // board:d8:white:rook
                Id(0x7e18_454e_2ae5_00f7_b085_3a5c_0aeb_0d8d), // board:d8:white:queen
                Id(0x05d6_d85f_9680_43f7_44ab_f1b2_c81e_f869), // board:d8:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x907f_d2ee_7d45_7513_5ac7_6106_e909_4558), // board:e8:black:pawn
                Id(0x9f21_7f2a_a345_0c9d_6c61_c3b4_7eb0_3216), // board:e8:black:knight
                Id(0x853e_b147_4876_5f25_8936_ee15_8077_961e), // board:e8:black:bishop
                Id(0xd402_1bea_e67e_52e2_bb81_dc9d_b8e2_30e4), // board:e8:black:rook
                Id(0xc7b7_3be1_0925_1499_0317_f142_281c_083c), // board:e8:black:queen
                Id(0x0dfe_ba6b_2fd9_983c_2d0a_f27c_163d_2e10), // board:e8:black:king
            ]),
            RoleTable::new([
                Id(0xde15_772f_e9ed_fdd9_f6a9_243f_e791_15a2), // board:e8:white:pawn
                Id(0xe95d_ca0a_4662_6377_ad15_2cc7_d678_dbb9), // board:e8:white:knight
                Id(0x86d3_24e7_6a08_94de_6b39_3e97_295a_5ed4), // board:e8:white:bishop
                Id(0xaf02_b3fe_171b_36e9_853b_f503_7e5f_8d07), // board:e8:white:rook
                Id(0x2a5f_a363_2985_a8f2_8466_1946_498e_2b84), // board:e8:white:queen
                Id(0xf5bd_1ce0_61f3_2640_872f_ac37_437b_da01), // board:e8:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x1472_f9d8_64b8_6c78_9c56_f9f4_bbf4_5d3d), // board:f8:black:pawn
                Id(0xb99a_44b7_38df_94ec_3ab1_8b07_c041_16c8), // board:f8:black:knight
                Id(0x129e_9b70_7020_2222_e332_0202_2d5a_ad43), // board:f8:black:bishop
                Id(0xde7f_c663_d760_e7e6_2b30_e21e_b25f_cb86), // board:f8:black:rook
                Id(0x5ae5_b60c_ec37_2324_d5da_eea9_621f_2f54), // board:f8:black:queen
                Id(0xcb8c_4600_2a00_16d9_8555_fb52_f13f_564c), // board:f8:black:king
            ]),
            RoleTable::new([
                Id(0x503e_d4b2_8dd3_bbdd_81a9_2102_59b1_9df1), // board:f8:white:pawn
                Id(0x2519_904d_b31d_42ed_f665_c5e1_fd68_89eb), // board:f8:white:knight
                Id(0x01a0_4701_137f_6937_3163_33d5_6715_54e9), // board:f8:white:bishop
                Id(0x3eee_74b0_8df3_efdc_89c5_065f_1115_07e9), // board:f8:white:rook
                Id(0xfd5b_28fc_34ae_7c60_b48f_a3f1_61d4_7f26), // board:f8:white:queen
                Id(0xd63f_4cbd_7c0e_4d67_fcc8_dae6_282c_e8d3), // board:f8:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0x0c0f_4f28_c85b_0744_8061_b15f_34ef_bf41), // board:g8:black:pawn
                Id(0x9a58_6c81_6349_167b_7d1c_4084_373c_ec6e), // board:g8:black:knight
                Id(0x7326_26af_dfbd_a6b0_345b_876e_fecf_6db6), // board:g8:black:bishop
                Id(0x705a_bc06_0a51_f3e7_73a4_6a50_4a77_4229), // board:g8:black:rook
                Id(0xf89d_54f6_2ede_5482_721c_48ac_467d_299e), // board:g8:black:queen
                Id(0xef10_f8d3_47e4_4812_2b4e_ab93_ed66_7e15), // board:g8:black:king
            ]),
            RoleTable::new([
                Id(0x6b41_5420_e1e3_799f_eab3_8b7f_f281_dc04), // board:g8:white:pawn
                Id(0x2fe9_82b6_4e61_ae9a_6dcf_d831_5483_29de), // board:g8:white:knight
                Id(0xfdf7_938e_e3d4_ccc0_400b_8f0f_abab_f3ff), // board:g8:white:bishop
                Id(0x9f77_5d60_096c_dd8e_ad7d_8c87_763c_be06), // board:g8:white:rook
                Id(0xfb1e_4c66_1e19_c771_cf44_1e9f_f903_53fd), // board:g8:white:queen
                Id(0x4c8e_2a30_bcc4_2a0a_2b95_4ded_9bf8_3618), // board:g8:white:king
            ]),
        ]),
        PlayerTable::new([
            RoleTable::new([
                Id(0xc6d0_7a3e_b63e_7888_1927_3c5b_0d45_2057), // board:h8:black:pawn
                Id(0x6b30_757b_af9b_1279_8d53_fadf_7ffd_4509), // board:h8:black:knight
                Id(0x5729_be50_6609_2d01_2b29_b674_6da3_b840), // board:h8:black:bishop
                Id(0x059c_5ec2_c09f_4263_e5d8_e9cf_02a4_5670), // board:h8:black:rook
                Id(0xcacc_3e17_5a3b_03c5_d603_b23f_f5f9_3cb2), // board:h8:black:queen
                Id(0x81d4_7c2e_b8a6_ff79_4beb_ab87_461f_ff65), // board:h8:black:king
            ]),
            RoleTable::new([
                Id(0x8ed6_37d8_42c3_ab37_cc6e_d265_87d8_2d06), // board:h8:white:pawn
                Id(0x818b_5fb9_7e9d_25b3_18af_9b5c_a93d_079c), // board:h8:white:knight
                Id(0xbf50_8a03_2464_d249_6d95_72b2_b822_0a79), // board:h8:white:bishop
                Id(0xbfce_cf5e_c7b2_2e32_5051_0416_318c_c45e), // board:h8:white:rook
                Id(0x3c72_8293_9fed_c463_5ba2_3e7e_0af0_22c6), // board:h8:white:queen
                Id(0x2f29_5b66_7a6f_7a59_18f5_81c9_01da_af8b), // board:h8:white:king
            ]),
        ]),
    ]),
    turn: PlayerTable::new([
        Id(0x24f1_5a0b_e435_f689_57b8_9360_2f26_aaa2), // turn:black
        Id(0x70cb_00ab_210b_730b_eeca_73d3_dc25_dcc6), // turn:white
    ]),
    castle: PlayerTable::new([
        SideTable::new([
            Id(0x6c7d_e5ef_d10d_7f35_5831_68f7_d2b3_70e4), // castle:black:king
            Id(0x1896_084f_e096_0bcc_c652_7810_9597_147b), // castle:black:queen
        ]),
        SideTable::new([
            Id(0x11f8_530c_cc9a_0422_8c6d_5490_400b_4905), // castle:white:king
            Id(0x52ea_807b_7fe5_29f5_76ea_09bf_1e42_8f1a), // castle:white:queen
        ]),
    ]),
    en_passant: EnPassant {
        none: Id(0xb924_9a46_dcf2_74ef_6dcf_8e3d_4fab_74c3), // en-passant:none
        square: en_passant::SquareTable::new([
            Id(0x394d_a7d0_d3df_9e3a_8657_d305_a551_5d0d), // en-passant:a3
            Id(0x89b7_e452_7bc8_92c5_f7d7_c140_2133_ab02), // en-passant:b3
            Id(0xfa68_7866_c405_3387_485f_b2d1_832c_1561), // en-passant:c3
            Id(0x3738_6c00_6809_933f_a366_3be7_6959_ac02), // en-passant:d3
            Id(0xcc89_d5c9_2c9c_e46e_6439_1cab_c7f6_7564), // en-passant:e3
            Id(0x121c_388d_2971_3744_cb12_03ef_92fb_3de8), // en-passant:f3
            Id(0xb34e_4463_93f8_98b8_60e3_dbb3_ec89_a0ea), // en-passant:g3
            Id(0xb2b6_d95c_2d21_0d0e_7005_720e_aa64_f1dd), // en-passant:h3
            Id(0x8490_a269_a8a4_1e0f_0cd6_7db2_17ee_9af4), // en-passant:a6
            Id(0x0492_6f96_7d4d_c98f_1e2e_09cc_d95e_92ed), // en-passant:b6
            Id(0x6c27_1318_7393_3ef3_5bed_a74d_8bf6_08be), // en-passant:c6
            Id(0x3c81_d2de_cb83_a68c_27c2_e7b5_8a41_9ed6), // en-passant:d6
            Id(0xd9dd_c82c_6ad1_eef8_6184_f4c6_4699_ea40), // en-passant:e6
            Id(0x71bb_e859_58fb_a5ab_9c71_8c2e_390a_247c), // en-passant:f6
            Id(0x2cf2_e423_591c_5d90_fe1a_e72e_96cc_20c7), // en-passant:g6
            Id(0xa4f9_c5dd_8670_7adb_f4af_18df_a5d3_faf1), // en-passant:h6
        ]),
    },
    variant: Variant {
        chess: Id(0x5dc5_6059_40db_1936_1955_9425_07cb_cf9a), // variant:chess
        freestyle: Id(0x8b30_2f4f_e807_5e47_a43b_6953_bbd8_3736), // variant:freestyle
    },
};
